# QIMED — Heisenberg com nested temporal, PCA e benchmarks clássicos

Este notebook é derivado de `QIMED_testes-quantum_nested_shap.ipynb`, sem modificar o original.

O notebook está dividido em duas partes independentes:

- **Parte I — 1.000 amostras:** benchmark clássico com todas as features, PCA-12, SHAP-12 e SHAP-36; depois Heisenberg 13q com PCA-12.
- **Parte II — 2.000 amostras:** benchmark clássico com todas as features, PCA-12, PCA-36, SHAP-12 e SHAP-36; depois Heisenberg 19q com PCA-36 e Heisenberg 37q com PCA-36/MPS.

Em todos os experimentos, preprocessing, PCA/SHAP e classificador são ajustados apenas no treino do respectivo split temporal. Nas camadas quânticas, PCA é usado somente para produzir a entrada da PQFM: o cenário clássico usa todas as features preprocessadas, o quantum-only usa todas as features quânticas e o híbrido concatena todas as clássicas com todas as quânticas. As camadas Heisenberg usam um circuito congelado por arquitetura e caches quânticos específicos das representações leakage-safe de cada fold.

In [1]:
import json
import pickle
import re
import time
import warnings
from pathlib import Path
from IPython.display import display

import numpy as np
import pandas as pd
import shap
from scipy.stats import t as student_t
from scipy.stats import wilcoxon

from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import ParameterGrid, StratifiedShuffleSplit, TimeSeriesSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from pqfmlib import HeisenbergProjectiveQFM

warnings.filterwarnings("ignore")

RANDOM_STATE = 42
OUTER_SPLITS = 10
INNER_SPLITS = 3
SCORING = "average_precision"
SHOTS = 4096
METRICS = (
    "ROC-AUC", "PR-AUC", "Accuracy", "Precision",
    "Recall", "F1", "Specificity",
)

OUTPUT_ROOT = Path("outputs")
CHECKPOINT_DIR = OUTPUT_ROOT / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

/home/rafael/projects/pqfmlib-api/.venv_gpu/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Dataset e colunas

O dataset é carregado uma única vez. Cada parte cria sua própria amostra estratificada e depois restaura a ordem temporal por `period_start`.

In [2]:
DATA_PATH = Path("./data/dataset_modelo_readmissao.parquet")
TARGET_COL = "readmitted_30d"

FEATURE_COLS = [
    "age_at_enc", "gender", "race", "deceased", "marital_status",
    "class_code", "enc_type_grp", "has_reason",
    "n_enc_total", "n_enc_30d", "n_enc_90d", "n_enc_365d",
    "days_since_last", "had_emer_90d", "had_imp_90d",
    "month", "quarter", "day_of_week", "is_weekend",
    "has_renal_disease", "has_diabetes", "has_hypertension", "has_mental_health",
    "n_conditions_total", "n_conditions_active",
    "last_hba1c", "last_egfr", "last_systolic_bp", "last_diastolic_bp", "last_bmi",
    "n_labs_90d", "n_vitals_90d",
    "n_procedures_90d", "n_procedures_365d", "had_surgical_90d", "had_dialysis_90d",
]

NUM_COLS = [
    "age_at_enc", "n_enc_total", "n_enc_30d", "n_enc_90d", "n_enc_365d",
    "days_since_last", "n_conditions_total", "n_conditions_active",
    "n_procedures_90d", "n_procedures_365d", "n_labs_90d", "n_vitals_90d",
]
LAB_COLS = [
    "last_hba1c", "last_egfr", "last_systolic_bp", "last_diastolic_bp", "last_bmi",
]
CAT_COLS = [
    "gender", "race", "marital_status", "class_code", "enc_type_grp",
    "month", "day_of_week", "quarter",
]
BIN_COLS = [
    "deceased", "has_reason", "had_emer_90d", "had_imp_90d",
    "has_renal_disease", "has_diabetes", "has_hypertension", "has_mental_health",
    "had_surgical_90d", "had_dialysis_90d", "is_weekend",
]

df = pd.read_parquet(DATA_PATH)
print(f"Dataset completo: {df.shape}")
print(f"Distribuição: {df[TARGET_COL].value_counts(normalize=True).sort_index().round(4).to_dict()}")

Dataset completo: (7746, 43)
Distribuição: {0: 0.3195, 1: 0.6805}

## 2. Esquema metodológico

```text
TimeSeriesSplit externo: 10 folds
│
├── outer train
│   └── TimeSeriesSplit interno: 3 folds
│       ├── fit preprocessing no inner train
│       ├── fit PCA e/ou SHAP no inner train
│       ├── transform do inner validation
│       └── tuning por Average Precision
│
└── outer refit
    ├── refit preprocessing + PCA/SHAP no outer train completo
    ├── transform do outer test
    └── métricas finais do fold
```

A Heisenberg não usa MI. Seu circuito é preparado uma única vez por arquitetura. Contudo, `transform()` é aplicado separadamente às representações PCA específicas de cada fold, pois o preprocessing e a PCA continuam sendo ajustados apenas no treino.

Nos experimentos Heisenberg, PCA serve exclusivamente como entrada do mapa quântico. A comparação usa sempre: clássico = todas as features preprocessadas; quantum-only = todas as features quânticas; híbrido = todas as clássicas + todas as quânticas.

## 3. Funções comuns: amostragem, preprocessing, PCA e SHAP

In [3]:
def stratified_temporal_sample(
    frame,
    n_samples,
    target_col=TARGET_COL,
    random_state=RANDOM_STATE,
):
    if len(frame) < n_samples:
        raise ValueError(
            f"O dataset possui {len(frame)} linhas; são necessárias pelo menos {n_samples}."
        )
    ordered = (
        frame.sort_values("period_start", kind="mergesort")
        .reset_index()
        .rename(columns={"index": "source_index"})
    )
    splitter = StratifiedShuffleSplit(
        n_splits=1,
        train_size=n_samples,
        random_state=random_state,
    )
    sample_idx, _ = next(splitter.split(ordered, ordered[target_col]))
    return (
        ordered.iloc[sample_idx]
        .sort_values("period_start", kind="mergesort")
        .reset_index(drop=True)
    )


def make_outer_folds(X, n_splits=OUTER_SPLITS):
    splitter = TimeSeriesSplit(n_splits=n_splits)
    return [(train.copy(), test.copy()) for train, test in splitter.split(X)]


def describe_nested_sizes(outer_folds):
    rows = []
    for outer_fold, (train_idx, test_idx) in enumerate(outer_folds, 1):
        inner_sizes = [
            len(inner_train)
            for inner_train, _ in TimeSeriesSplit(n_splits=INNER_SPLITS).split(train_idx)
        ]
        rows.append({
            "outer_fold": outer_fold,
            "outer_train": len(train_idx),
            "outer_test": len(test_idx),
            "inner_train_sizes": inner_sizes,
        })
    return pd.DataFrame(rows)


def build_preprocessor():
    return ColumnTransformer(
        transformers=[
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]), NUM_COLS),
            ("labs", Pipeline([
                ("imputer", SimpleImputer(strategy="median", add_indicator=True)),
                ("scaler", StandardScaler()),
            ]), LAB_COLS),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore")),
            ]), CAT_COLS),
            ("bin", Pipeline([
                ("imputer", SimpleImputer(strategy="constant", fill_value=0)),
            ]), BIN_COLS),
        ]
    )


def _as_dense_frame(values, columns):
    if hasattr(values, "toarray"):
        values = values.toarray()
    return pd.DataFrame(
        np.asarray(values, dtype=float),
        columns=list(columns),
    ).reset_index(drop=True)


def fit_preprocessing(X_train):
    preprocessor = build_preprocessor()
    transformed = preprocessor.fit_transform(X_train)
    columns = list(preprocessor.get_feature_names_out())
    X_frame = _as_dense_frame(transformed, columns)

    final_scaler = StandardScaler()
    X_scaled = pd.DataFrame(
        final_scaler.fit_transform(X_frame),
        columns=columns,
    )
    fitted = {
        "preprocessor": preprocessor,
        "final_scaler": final_scaler,
        "columns": columns,
    }
    return fitted, X_scaled


def transform_preprocessing(fitted, X):
    transformed = fitted["preprocessor"].transform(X)
    X_frame = _as_dense_frame(transformed, fitted["columns"])
    return pd.DataFrame(
        fitted["final_scaler"].transform(X_frame),
        columns=fitted["columns"],
    )


def fit_pca_reducer(X_train, n_components):
    max_centered_rank = min(X_train.shape[1], X_train.shape[0] - 1)
    if n_components > max_centered_rank:
        raise ValueError(
            f"PCA-{n_components} requer posto centralizado >= {n_components}, "
            f"mas este treino permite no máximo {max_centered_rank}."
        )
    reducer = PCA(n_components=n_components, svd_solver="full")
    values = reducer.fit_transform(X_train)
    columns = [f"PC{i:03d}" for i in range(1, n_components + 1)]
    return {"pca": reducer, "columns": columns}, pd.DataFrame(values, columns=columns)


def transform_pca(fitted, X):
    return pd.DataFrame(
        fitted["pca"].transform(X),
        columns=fitted["columns"],
    ).reset_index(drop=True)


def _positive_class_shap_matrix(shap_output, n_samples, n_features):
    values = getattr(shap_output, "values", shap_output)
    if isinstance(values, list):
        values = values[-1]
    values = np.asarray(values)
    if values.ndim == 3:
        if values.shape[:2] == (n_samples, n_features):
            values = values[:, :, -1]
        elif values.shape[1:] == (n_samples, n_features):
            values = values[-1]
        else:
            raise ValueError(f"Formato SHAP 3D não reconhecido: {values.shape}")
    if values.shape != (n_samples, n_features):
        raise ValueError(
            f"Formato SHAP inesperado: {values.shape}; "
            f"esperado {(n_samples, n_features)}"
        )
    return values


def fit_shap_ranker(X_train, y_train, max_features=36):
    if max_features > X_train.shape[1]:
        raise ValueError(
            f"SHAP-{max_features} solicitado, mas o preprocessing gerou "
            f"apenas {X_train.shape[1]} colunas."
        )
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=6,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)
    shap_output = shap.TreeExplainer(model)(X_train, check_additivity=False)
    shap_matrix = _positive_class_shap_matrix(
        shap_output,
        len(X_train),
        X_train.shape[1],
    )
    importance = pd.Series(
        np.abs(shap_matrix).mean(axis=0),
        index=X_train.columns,
    ).sort_values(ascending=False, kind="mergesort")
    return {
        "model": model,
        "ranking": importance.index.tolist(),
        "importance": importance,
    }


def transform_shap_top(fitted, X, n_features):
    selected = fitted["ranking"][:n_features]
    return X.loc[:, selected].copy().reset_index(drop=True)


def fit_representations(X_train_raw, y_train, include_pca36):
    preprocessing, X_all = fit_preprocessing(X_train_raw)

    max_pca_components = 36 if include_pca36 else 12
    pca, X_pca_max = fit_pca_reducer(X_all, max_pca_components)
    shap_ranker = fit_shap_ranker(
        X_all,
        y_train.reset_index(drop=True),
        max_features=36,
    )

    representations = {
        "all_features": X_all.reset_index(drop=True),
        "pca12": X_pca_max.iloc[:, :12].copy().reset_index(drop=True),
        "shap12": transform_shap_top(shap_ranker, X_all, 12),
        "shap36": transform_shap_top(shap_ranker, X_all, 36),
    }
    if include_pca36:
        representations["pca36"] = X_pca_max.copy().reset_index(drop=True)

    fitted = {
        "preprocessing": preprocessing,
        "pca": pca,
        "shap": shap_ranker,
        "include_pca36": include_pca36,
    }
    return fitted, representations


def transform_representations(fitted, X_raw):
    X_all = transform_preprocessing(fitted["preprocessing"], X_raw)
    X_pca_max = transform_pca(fitted["pca"], X_all)
    representations = {
        "all_features": X_all.reset_index(drop=True),
        "pca12": X_pca_max.iloc[:, :12].copy().reset_index(drop=True),
        "shap12": transform_shap_top(fitted["shap"], X_all, 12),
        "shap36": transform_shap_top(fitted["shap"], X_all, 36),
    }
    if fitted["include_pca36"]:
        representations["pca36"] = X_pca_max.copy().reset_index(drop=True)
    return representations

## 4. Funções comuns: tuning, métricas, caches e estatística

In [4]:
CLASSIFIER_GRID = {
    "n_estimators": [50, 100],
    "max_depth": [3, 5],
    "learning_rate": [0.05, 0.1],
}


def compute_metrics(y_true, y_pred, y_proba):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    y_proba = np.asarray(y_proba)
    roc_auc = (
        roc_auc_score(y_true, y_proba)
        if np.unique(y_true).size == 2 else np.nan
    )
    pr_auc = (
        average_precision_score(y_true, y_proba)
        if np.any(y_true == 1) else np.nan
    )
    tn, fp, fn, tp = confusion_matrix(
        y_true, y_pred, labels=[0, 1]
    ).ravel()
    specificity = tn / (tn + fp) if (tn + fp) else np.nan
    return {
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "Specificity": specificity,
    }


def candidate_key(params):
    return json.dumps(params, sort_keys=True)


def fit_and_score_classifier(
    X_train,
    y_train,
    X_validation,
    y_validation,
    params,
):
    classifier = GradientBoostingClassifier(
        random_state=RANDOM_STATE,
        **params,
    )
    classifier.fit(X_train, y_train)
    probabilities = classifier.predict_proba(X_validation)[:, 1]
    return average_precision_score(y_validation, probabilities)


def prepare_classical_benchmark(
    X,
    y,
    outer_folds,
    sample_label,
    representations,
    include_pca36,
):
    candidates = list(ParameterGrid(CLASSIFIER_GRID))
    cached_folds = []
    fold_rows = []
    tuning_rows = []

    for outer_fold, (train_idx, test_idx) in enumerate(outer_folds, 1):
        print(
            f"[{sample_label}/clássico] outer fold "
            f"{outer_fold}/{len(outer_folds)}"
        )
        X_outer_train_raw = X.iloc[train_idx].copy()
        X_outer_test_raw = X.iloc[test_idx].copy()
        y_outer_train = y.iloc[train_idx].reset_index(drop=True)
        y_outer_test = y.iloc[test_idx].reset_index(drop=True)

        inner_folds = []
        scores = {
            representation: {
                candidate_key(params): [] for params in candidates
            }
            for representation in representations
        }

        inner_cv = TimeSeriesSplit(n_splits=INNER_SPLITS)
        for inner_fold, (inner_train_idx, inner_validation_idx) in enumerate(
            inner_cv.split(X_outer_train_raw), 1
        ):
            X_inner_train_raw = X_outer_train_raw.iloc[inner_train_idx].copy()
            X_inner_validation_raw = X_outer_train_raw.iloc[inner_validation_idx].copy()
            y_inner_train = y_outer_train.iloc[inner_train_idx].reset_index(drop=True)
            y_inner_validation = y_outer_train.iloc[inner_validation_idx].reset_index(drop=True)

            fitted_stack, train_representations = fit_representations(
                X_inner_train_raw,
                y_inner_train,
                include_pca36=include_pca36,
            )
            validation_representations = transform_representations(
                fitted_stack,
                X_inner_validation_raw,
            )

            for representation in representations:
                for params in candidates:
                    key = candidate_key(params)
                    scores[representation][key].append(
                        fit_and_score_classifier(
                            train_representations[representation],
                            y_inner_train,
                            validation_representations[representation],
                            y_inner_validation,
                            params,
                        )
                    )

            inner_folds.append({
                "inner_fold": inner_fold,
                "train_representations": train_representations,
                "validation_representations": validation_representations,
                "y_train": y_inner_train,
                "y_validation": y_inner_validation,
            })

        best_params = {}
        for representation in representations:
            mean_scores = {
                key: float(np.mean(values))
                for key, values in scores[representation].items()
            }
            best_key = max(mean_scores, key=mean_scores.get)
            best_params[representation] = json.loads(best_key)
            for key, values in scores[representation].items():
                tuning_rows.append({
                    "sample": sample_label,
                    "outer_fold": outer_fold,
                    "representation": representation,
                    "params": key,
                    "mean_inner_average_precision": np.mean(values),
                    "std_inner_average_precision": np.std(values, ddof=1),
                })

        fitted_outer, outer_train_representations = fit_representations(
            X_outer_train_raw,
            y_outer_train,
            include_pca36=include_pca36,
        )
        outer_test_representations = transform_representations(
            fitted_outer,
            X_outer_test_raw,
        )

        classic_metrics = {}
        for representation in representations:
            params = best_params[representation]
            classifier = GradientBoostingClassifier(
                random_state=RANDOM_STATE,
                **params,
            )
            classifier.fit(
                outer_train_representations[representation],
                y_outer_train,
            )
            prediction = classifier.predict(
                outer_test_representations[representation]
            )
            probability = classifier.predict_proba(
                outer_test_representations[representation]
            )[:, 1]
            metrics = compute_metrics(
                y_outer_test,
                prediction,
                probability,
            )
            classic_metrics[representation] = metrics
            fold_rows.append({
                "sample": sample_label,
                "representation": representation,
                "outer_fold": outer_fold,
                "n_train": len(train_idx),
                "n_test": len(test_idx),
                "test_start_position": int(test_idx[0]),
                "test_end_position": int(test_idx[-1]),
                "best_params": json.dumps(params, sort_keys=True),
                **metrics,
            })

        cached_folds.append({
            "outer_fold": outer_fold,
            "train_idx": train_idx.copy(),
            "test_idx": test_idx.copy(),
            "inner_folds": inner_folds,
            "outer_train_representations": outer_train_representations,
            "outer_test_representations": outer_test_representations,
            "y_outer_train": y_outer_train,
            "y_outer_test": y_outer_test,
            "best_params": best_params,
            "classic_metrics": classic_metrics,
        })

        checkpoint = {
            "sample": sample_label,
            "fold_results": pd.DataFrame(fold_rows),
            "tuning_results": pd.DataFrame(tuning_rows),
        }
        with open(
            CHECKPOINT_DIR / f"classical_benchmark_{sample_label}_fold_{outer_fold:02d}.pkl",
            "wb",
        ) as handle:
            pickle.dump(checkpoint, handle)

    return {
        "sample": sample_label,
        "representations": tuple(representations),
        "folds": cached_folds,
        "fold_results": pd.DataFrame(fold_rows),
        "tuning_results": pd.DataFrame(tuning_rows),
    }

In [5]:
def _mean_std_ci(values, confidence=0.95):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    n = len(values)
    mean = float(np.mean(values)) if n else np.nan
    std = float(np.std(values, ddof=1)) if n > 1 else np.nan
    if n > 1:
        critical = student_t.ppf((1 + confidence) / 2, df=n - 1)
        margin = critical * std / np.sqrt(n)
        return n, mean, std, mean - margin, mean + margin
    return n, mean, std, np.nan, np.nan


def summarize_classical_results(fold_results):
    rows = []
    for (sample, representation), group in fold_results.groupby(
        ["sample", "representation"], sort=False
    ):
        for metric in METRICS:
            n, mean, std, ci_low, ci_high = _mean_std_ci(group[metric])
            rows.append({
                "sample": sample,
                "representation": representation,
                "metric": metric,
                "n_folds": n,
                "mean": mean,
                "std": std,
                "ci95_low": ci_low,
                "ci95_high": ci_high,
            })
    return pd.DataFrame(rows)


def _comparison_status(delta_mean, p_value):
    significant = bool(p_value < 0.05) if np.isfinite(p_value) else False
    if np.isclose(delta_mean, 0):
        return "Sem alteração"
    if significant and delta_mean > 0:
        return "✅ MELHORA SIGNIFICATIVA"
    if significant and delta_mean < 0:
        return "⚠️ PIORA SIGNIFICATIVA"
    if delta_mean > 0:
        return "↑ Melhora (não sig.)"
    return "↓ Piora (não sig.)"


def classical_statistical_analysis(
    fold_results,
    title,
    baseline="all_features",
    n_bootstrap=2_000,
):
    rng = np.random.default_rng(RANDOM_STATE)
    rows = []
    sample = fold_results["sample"].iloc[0]
    challengers = [
        value for value in fold_results["representation"].drop_duplicates()
        if value != baseline
    ]

    for challenger in challengers:
        for metric in METRICS:
            paired = fold_results.pivot(
                index="outer_fold",
                columns="representation",
                values=metric,
            )[[baseline, challenger]].dropna()
            base = paired[baseline].to_numpy(dtype=float)
            case = paired[challenger].to_numpy(dtype=float)
            delta = case - base
            if len(delta) < 2:
                statistic, p_value = np.nan, np.nan
            elif np.allclose(delta, 0):
                statistic, p_value = 0.0, 1.0
            else:
                statistic, p_value = wilcoxon(case, base, alternative="two-sided")
            indices = rng.integers(0, len(delta), size=(n_bootstrap, len(delta)))
            bootstrap_means = delta[indices].mean(axis=1)
            ci_low, ci_high = np.percentile(bootstrap_means, [2.5, 97.5])
            delta_mean = float(np.mean(delta))
            rows.append({
                "Amostra": sample,
                "Comparação": f"{baseline} vs {challenger}",
                "Métrica": metric,
                "Folds": len(delta),
                "Média Base": float(np.mean(base)),
                "Média Caso": float(np.mean(case)),
                "Δ Médio": delta_mean,
                "IC95 low": float(ci_low),
                "IC95 high": float(ci_high),
                "Estatística W": float(statistic) if np.isfinite(statistic) else np.nan,
                "p-valor": float(p_value) if np.isfinite(p_value) else np.nan,
                "Status": _comparison_status(delta_mean, p_value),
            })

    result = pd.DataFrame(rows)
    print(f"\n{'=' * 96}\n  {title}\n{'=' * 96}")
    if result.empty:
        print("Nenhuma comparação pareada disponível.")
        return result
    table = result.copy()
    table["IC95% Δ"] = table.apply(
        lambda row: f"[{row['IC95 low']:.4f}, {row['IC95 high']:.4f}]",
        axis=1,
    )
    for column in ["Média Base", "Média Caso", "Δ Médio", "p-valor"]:
        table[column] = table[column].round(4)
    print(table[[
        "Comparação", "Métrica", "Média Base", "Média Caso",
        "Δ Médio", "IC95% Δ", "p-valor", "Status",
    ]].to_string(index=False))
    return result


def summarize_quantum_results(fold_results):
    rows = []
    for (config, scenario), group in fold_results.groupby(
        ["config", "scenario"], sort=False
    ):
        for metric in METRICS:
            n, mean, std, ci_low, ci_high = _mean_std_ci(group[metric])
            rows.append({
                "config": config,
                "scenario": scenario,
                "metric": metric,
                "n_folds": n,
                "mean": mean,
                "std": std,
                "ci95_low": ci_low,
                "ci95_high": ci_high,
            })
    return pd.DataFrame(rows)


def quantum_statistical_analysis(
    fold_results,
    title,
    n_bootstrap=2_000,
):
    rng = np.random.default_rng(RANDOM_STATE)
    comparisons = [
        ("classica", "quantum_only", "Clássico vs Quantum-Only"),
        ("classica", "hibrida", "Clássico vs Híbrido"),
    ]
    rows = []
    for metric in METRICS:
        paired = fold_results.pivot(
            index="outer_fold",
            columns="scenario",
            values=metric,
        )
        for baseline, challenger, label in comparisons:
            pair = paired[[baseline, challenger]].dropna()
            base = pair[baseline].to_numpy(dtype=float)
            case = pair[challenger].to_numpy(dtype=float)
            delta = case - base
            if len(delta) < 2:
                statistic, p_value = np.nan, np.nan
            elif np.allclose(delta, 0):
                statistic, p_value = 0.0, 1.0
            else:
                statistic, p_value = wilcoxon(case, base, alternative="two-sided")
            indices = rng.integers(0, len(delta), size=(n_bootstrap, len(delta)))
            bootstrap_means = delta[indices].mean(axis=1)
            ci_low, ci_high = np.percentile(bootstrap_means, [2.5, 97.5])
            delta_mean = float(np.mean(delta))
            rows.append({
                "Comparação": label,
                "Métrica": metric,
                "Folds": len(delta),
                "Média Base": float(np.mean(base)),
                "Média Caso": float(np.mean(case)),
                "Δ Médio": delta_mean,
                "IC95 low": float(ci_low),
                "IC95 high": float(ci_high),
                "Estatística W": float(statistic) if np.isfinite(statistic) else np.nan,
                "p-valor": float(p_value) if np.isfinite(p_value) else np.nan,
                "Status": _comparison_status(delta_mean, p_value),
            })

    result = pd.DataFrame(rows)
    print(f"\n{'=' * 96}\n  {title}\n{'=' * 96}")
    table = result.copy()
    table["IC95% Δ"] = table.apply(
        lambda row: f"[{row['IC95 low']:.4f}, {row['IC95 high']:.4f}]",
        axis=1,
    )
    for column in ["Média Base", "Média Caso", "Δ Médio", "p-valor"]:
        table[column] = table[column].round(4)
    print(table[[
        "Comparação", "Métrica", "Média Base", "Média Caso",
        "Δ Médio", "IC95% Δ", "p-valor", "Status",
    ]].to_string(index=False))
    return result

# PARTE I — 1.000 amostras

Esta parte usa uma amostra estratificada de 1.000 registros. O benchmark clássico contém `all_features`, `pca12`, `shap12` e `shap36`. A camada quântica usa exclusivamente PCA-12.

In [6]:
sampled_1000 = stratified_temporal_sample(df, n_samples=1_000)
X_1000 = sampled_1000[FEATURE_COLS].copy()
y_1000 = sampled_1000[TARGET_COL].astype(int).copy()
OUTER_FOLDS_1000 = make_outer_folds(X_1000)

print(f"Amostra 1.000: {X_1000.shape}")
print(f"Distribuição: {y_1000.value_counts(normalize=True).sort_index().round(4).to_dict()}")
print(f"Período: {sampled_1000['period_start'].min()} → {sampled_1000['period_start'].max()}")
display(describe_nested_sizes(OUTER_FOLDS_1000))

assert min(
    min(sizes)
    for sizes in describe_nested_sizes(OUTER_FOLDS_1000)["inner_train_sizes"]
) >= 13, "A menor janela deve permitir 12 componentes após centralização."

Amostra 1.000: (1000, 36)
Distribuição: {0: 0.32, 1: 0.68}
Período: 1952-01-18 02:54:36+00:00 → 2023-03-17 02:54:36+00:00

   outer_fold  outer_train  outer_test inner_train_sizes
0           1          100          90      [25, 50, 75]
1           2          190          90     [49, 96, 143]
2           3          280          90    [70, 140, 210]
3           4          370          90    [94, 186, 278]
4           5          460          90   [115, 230, 345]
5           6          550          90   [139, 276, 413]
6           7          640          90   [160, 320, 480]
7           8          730          90   [184, 366, 548]
8           9          820          90   [205, 410, 615]
9          10          910          90   [229, 456, 683]

## Parte I.A — Benchmark clássico, 1.000 amostras

Os quatro pipelines usam os mesmos outer/inner folds e fazem tuning independente pelo mesmo grid.

In [7]:
REPRESENTATIONS_1000 = (
    "all_features",
    "pca12",
    "shap12",
    "shap36",
)
BENCHMARK_KEY_1000 = (
    id(X_1000),
    RANDOM_STATE,
    REPRESENTATIONS_1000,
    tuple((name, tuple(values)) for name, values in sorted(CLASSIFIER_GRID.items())),
)

benchmark_is_current = (
    "CLASSICAL_BENCHMARK_N1000" in globals()
    and CLASSICAL_BENCHMARK_N1000.get("cache_key") == BENCHMARK_KEY_1000
)

if benchmark_is_current:
    print("Benchmark clássico n1000 já existe; reutilizando cache.")
else:
    CLASSICAL_BENCHMARK_N1000 = prepare_classical_benchmark(
        X=X_1000,
        y=y_1000,
        outer_folds=OUTER_FOLDS_1000,
        sample_label="n1000",
        representations=REPRESENTATIONS_1000,
        include_pca36=False,
    )
    CLASSICAL_BENCHMARK_N1000["cache_key"] = BENCHMARK_KEY_1000

[n1000/clássico] outer fold 1/10
[n1000/clássico] outer fold 2/10
[n1000/clássico] outer fold 3/10
[n1000/clássico] outer fold 4/10
[n1000/clássico] outer fold 5/10
[n1000/clássico] outer fold 6/10
[n1000/clássico] outer fold 7/10
[n1000/clássico] outer fold 8/10
[n1000/clássico] outer fold 9/10
[n1000/clássico] outer fold 10/10

In [8]:
CLASSICAL_SUMMARY_N1000 = summarize_classical_results(
    CLASSICAL_BENCHMARK_N1000["fold_results"]
)
CLASSICAL_STATS_N1000 = classical_statistical_analysis(
    CLASSICAL_BENCHMARK_N1000["fold_results"],
    title="BENCHMARK CLÁSSICO — 1.000 AMOSTRAS — 10 OUTER FOLDS",
)

display(CLASSICAL_BENCHMARK_N1000["fold_results"])
display(CLASSICAL_SUMMARY_N1000)

================================================================================================
  BENCHMARK CLÁSSICO — 1.000 AMOSTRAS — 10 OUTER FOLDS
================================================================================================
            Comparação     Métrica  Média Base  Média Caso  Δ Médio            IC95% Δ  p-valor                 Status
 all_features vs pca12     ROC-AUC      0.8107      0.7573  -0.0534  [-0.0991, 0.0024]   0.0840     ↓ Piora (não sig.)
 all_features vs pca12      PR-AUC      0.8788      0.8660  -0.0128  [-0.0477, 0.0423]   0.0840     ↓ Piora (não sig.)
 all_features vs pca12    Accuracy      0.7567      0.6811  -0.0756 [-0.1178, -0.0400]   0.0039 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca12   Precision      0.8170      0.7870  -0.0300 [-0.0560, -0.0074]   0.0488 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca12      Recall      0.8030      0.7129  -0.0901 [-0.1730, -0.0259]   0.0195 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca12          F1      0.8081      0.7364  -0.0716 [-0.1294, -0.0307]   0.0039 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca12 Specificity      0.6689      0.6175  -0.0514  [-0.1269, 0.0239]   0.2031     ↓ Piora (não sig.)
all_features vs shap12     ROC-AUC      0.8107      0.8173   0.0066  [-0.0305, 0.0597]   0.1289   ↑ Melhora (não sig.)
all_features vs shap12      PR-AUC      0.8788      0.8883   0.0094  [-0.0246, 0.0632]   0.4922   ↑ Melhora (não sig.)
all_features vs shap12    Accuracy      0.7567      0.7500  -0.0067  [-0.0356, 0.0222]   0.7266     ↓ Piora (não sig.)
all_features vs shap12   Precision      0.8170      0.8294   0.0124  [-0.0119, 0.0402]   0.4922   ↑ Melhora (não sig.)
all_features vs shap12      Recall      0.8030      0.7736  -0.0294 [-0.0590, -0.0010]   0.0977     ↓ Piora (não sig.)
all_features vs shap12          F1      0.8081      0.7979  -0.0102  [-0.0343, 0.0139]   0.5566     ↓ Piora (não sig.)
all_features vs shap12 Specificity      0.6689      0.6901   0.0213  [-0.0384, 0.0840]   0.5703   ↑ Melhora (não sig.)
all_features vs shap36     ROC-AUC      0.8107      0.8109   0.0002  [-0.0210, 0.0314]   0.1309   ↑ Melhora (não sig.)
all_features vs shap36      PR-AUC      0.8788      0.8854   0.0066  [-0.0109, 0.0325]   0.4922   ↑ Melhora (não sig.)
all_features vs shap36    Accuracy      0.7567      0.7511  -0.0056  [-0.0233, 0.0089]   0.8125     ↓ Piora (não sig.)
all_features vs shap36   Precision      0.8170      0.8201   0.0031  [-0.0130, 0.0164]   0.6406   ↑ Melhora (não sig.)
all_features vs shap36      Recall      0.8030      0.7855  -0.0175  [-0.0426, 0.0065]   0.1562     ↓ Piora (não sig.)
all_features vs shap36          F1      0.8081      0.8009  -0.0072  [-0.0227, 0.0084]   0.3828     ↓ Piora (não sig.)
all_features vs shap36 Specificity      0.6689      0.6843   0.0154  [-0.0202, 0.0491]   0.2969   ↑ Melhora (não sig.)

,sample,representation,outer_fold,n_train,n_test,test_start_position,test_end_position,best_params,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1,Specificity
0,n1000,all_features,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.974085,0.997531,0.944444,0.987342,0.951220,0.968944,0.875000
1,n1000,pca12,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.850610,0.971805,0.900000,0.974026,0.914634,0.943396,0.750000
2,n1000,shap12,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.974085,0.997575,0.944444,0.975309,0.963415,0.969325,0.750000
3,n1000,shap36,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.972561,0.997396,0.944444,0.987342,0.951220,0.968944,0.875000
4,n1000,all_features,2,190,90,190,279,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.870694,0.933492,0.766667,0.839286,0.796610,0.817391,0.709677
5,n1000,pca12,2,190,90,190,279,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.845271,0.899316,0.555556,0.880000,0.372881,0.523810,0.903226
6,n1000,shap12,2,190,90,190,279,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.863587,0.911120,0.788889,0.884615,0.779661,0.828829,0.806452
7,n1000,shap36,2,190,90,190,279,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.864680,0.913887,0.766667,0.851852,0.779661,0.814159,0.741935
8,n1000,all_features,3,280,90,280,369,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.939001,0.980024,0.866667,0.910448,0.910448,0.910448,0.739130
9,n1000,pca12,3,280,90,280,369,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.924724,0.976402,0.877778,0.911765,0.925373,0.918519,0.739130
10,n1000,shap12,3,280,90,280,369,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.938352,0.980815,0.844444,0.895522,0.895522,0.895522,0.695652
11,n1000,shap36,3,280,90,280,369,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.937054,0.978933,0.866667,0.910448,0.910448,0.910448,0.739130
12,n1000,all_features,4,370,90,370,459,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.796875,0.924385,0.722222,0.867925,0.718750,0.786325,0.730769
13,n1000,pca12,4,370,90,370,459,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.723858,0.900670,0.666667,0.826923,0.671875,0.741379,0.653846
14,n1000,shap12,4,370,90,370,459,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.796274,0.929366,0.755556,0.920000,0.718750,0.807018,0.846154
15,n1000,shap36,4,370,90,370,459,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.777644,0.916787,0.722222,0.882353,0.703125,0.782609,0.769231
16,n1000,all_features,5,460,90,460,549,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.490196,0.570284,0.611111,0.637931,0.725490,0.678899,0.461538
17,n1000,pca12,5,460,90,460,549,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.647310,0.780922,0.566667,0.620000,0.607843,0.613861,0.512821
18,n1000,shap12,5,460,90,460,549,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.719960,0.800848,0.677778,0.729167,0.686275,0.707071,0.666667
19,n1000,shap36,5,460,90,460,549,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.615133,0.687484,0.622222,0.673469,0.647059,0.660000,0.589744
20,n1000,all_features,6,550,90,550,639,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.747500,0.870167,0.677778,0.781818,0.716667,0.747826,0.600000
21,n1000,pca12,6,550,90,550,639,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.653333,0.800757,0.633333,0.745455,0.683333,0.713043,0.533333
22,n1000,shap12,6,550,90,550,639,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.671944,0.821758,0.622222,0.782609,0.600000,0.679245,0.666667
23,n1000,shap36,6,550,90,550,639,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.708333,0.848091,0.633333,0.736842,0.700000,0.717949,0.500000
24,n1000,all_features,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.720930,0.722875,0.622222,0.632653,0.659574,0.645833,0.581395
25,n1000,pca12,7,640,90,640,729,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.626175,0.649812,0.577778,0.578947,0.702128,0.634615,0.441860
26,n1000,shap12,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.718209,0.669220,0.677778,0.680000,0.723404,0.701031,0.627907
27,n1000,shap36,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.709550,0.737204,0.655556,0.653846,0.723404,0.686869,0.581395
28,n1000,all_features,8,730,90,730,819,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.842937,0.899969,0.777778,0.770492,0.886792,0.824561,0.621622
29,n1000,pca12,8,730,90,730,819,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.829169,0.888516,0.733333,0.745763,0.830189,0.785714,0.594595
30,n1000,shap12,8,730,90,730,819,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.836818,0.905752,0.722222,0.733333,0.830189,0.778761,0.567568
31,n1000,shap36,8,730,90,730,819,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.806221,0.882070,0.711111,0.736842,0.792453,0.763636,0.594595
32,n1000,all_features,9,820,90,820,909,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.870945,0.960140,0.788889,0.903226,0.811594,0.854962,0.714286
33,n1000,pca12,9,820,90,820,909,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.762940,0.925585,0.666667,0.867925,0.666667,0.754098,0.666667
34,n1000,shap12,9,820,90,820,909,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.830918,0.948381,0.733333,0.868852,0.768116,0.815385,0.619048
35,n1000,shap36,9,820,90,820,909,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.861974,0.959047,0.800000,0.918033,0.811594,0.861538,0.761905
36,n1000,all_features,10,910,90,910,999,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.854155,0.929375,0.788889,0.838710,0.852459,0.845528,0.655172
37,n1000,pca12,10,910,90,910,999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.709723,0.865994,0.633333,0.718750,0.754098,0.736000,0.379310
38,n1000,shap12,10,910,90,910,999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.822781,0.917903,0.733333,0.824561,0.770492,0.796610,0.655172
39,n1000,shap36,10,910,90,910,999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.855851,0.932915,0.788889,0.850000,0.836066,0.842975,0.689655

,sample,representation,metric,n_folds,mean,std,ci95_low,ci95_high
0,n1000,all_features,ROC-AUC,10,0.810732,0.136739,0.712914,0.908549
1,n1000,all_features,PR-AUC,10,0.878824,0.132750,0.783860,0.973788
2,n1000,all_features,Accuracy,10,0.756667,0.103631,0.682534,0.830800
3,n1000,all_features,Precision,10,0.816983,0.114598,0.735004,0.898962
4,n1000,all_features,Recall,10,0.802960,0.096739,0.733757,0.872163
5,n1000,all_features,F1,10,0.808072,0.098562,0.737565,0.878579
6,n1000,all_features,Specificity,10,0.668859,0.111946,0.588778,0.748940
7,n1000,pca12,ROC-AUC,10,0.757311,0.101738,0.684532,0.830090
8,n1000,pca12,PR-AUC,10,0.865978,0.098874,0.795248,0.936708
9,n1000,pca12,Accuracy,10,0.681111,0.121947,0.593876,0.768347
10,n1000,pca12,Precision,10,0.786955,0.127626,0.695657,0.878254
11,n1000,pca12,Recall,10,0.712902,0.160816,0.597861,0.827943
12,n1000,pca12,F1,10,0.736444,0.129057,0.644122,0.828765
13,n1000,pca12,Specificity,10,0.617479,0.157719,0.504653,0.730304
14,n1000,shap12,ROC-AUC,10,0.817293,0.095939,0.748662,0.885923
15,n1000,shap12,PR-AUC,10,0.888274,0.098640,0.817711,0.958837
16,n1000,shap12,Accuracy,10,0.750000,0.092110,0.684109,0.815891
17,n1000,shap12,Precision,10,0.829397,0.095617,0.760996,0.897797
18,n1000,shap12,Recall,10,0.773582,0.104064,0.699139,0.848025
19,n1000,shap12,F1,10,0.797880,0.089655,0.733744,0.862015
20,n1000,shap12,Specificity,10,0.690129,0.086768,0.628058,0.752199
21,n1000,shap36,ROC-AUC,10,0.810900,0.110461,0.731881,0.889919
22,n1000,shap36,PR-AUC,10,0.885381,0.101820,0.812544,0.958219
23,n1000,shap36,Accuracy,10,0.751111,0.103730,0.676907,0.825315
24,n1000,shap36,Precision,10,0.820103,0.112796,0.739414,0.900792
25,n1000,shap36,Recall,10,0.785503,0.096329,0.716594,0.854412
26,n1000,shap36,F1,10,0.800913,0.098501,0.730449,0.871376
27,n1000,shap36,Specificity,10,0.684259,0.114262,0.602521,0.765997

## Parte I.B — Heisenberg 13q × PCA-12, GPU

Treze qubits formam uma cadeia com 12 arestas. As 12 componentes PCA ocupam exatamente um bloco. O circuito é ajustado uma única vez; as features quânticas são pré-calculadas para as representações PCA-12 específicas de cada fold.

In [10]:
# ── CONFIGURAÇÃO EDITÁVEL DESTA CÉLULA ──────────────────────────────
RUN_LABEL = "heisenberg_13q_pca12_n1000_gpu"
N_QUBITS = 13
N_PCA_COMPONENTS = 12
HEISENBERG_R = 2
HEISENBERG_ALPHA = 0.1
HEISENBERG_SHOTS = SHOTS
USE_TANH_SCALING = True
MEASURE_2LOCAL_DIAGONAL = False
CLASSICAL_BENCHMARK = CLASSICAL_BENCHMARK_N1000
PCA_REPRESENTATION = "pca12"
# ────────────────────────────────────────────────────────────────────

HEISENBERG_CACHE_KEY_13Q = (
    RUN_LABEL,
    id(CLASSICAL_BENCHMARK),
    RANDOM_STATE,
    N_QUBITS,
    N_PCA_COMPONENTS,
    HEISENBERG_R,
    HEISENBERG_ALPHA,
    HEISENBERG_SHOTS,
    USE_TANH_SCALING,
    MEASURE_2LOCAL_DIAGONAL,
)
cache_is_current = (
    "HEISENBERG_PCA_CACHE_13Q_N1000" in globals()
    and HEISENBERG_PCA_CACHE_13Q_N1000.get("cache_key")
    == HEISENBERG_CACHE_KEY_13Q
)

if cache_is_current:
    print("Cache Heisenberg 13q/PCA-12/n1000 já existe; reutilizando.")
else:
    HEISENBERG_PQFM_13Q = HeisenbergProjectiveQFM(
        name_file=RUN_LABEL,
        seed=RANDOM_STATE,
        ideal=True,
        simulation=True,
        fakebackend=False,
        shots=HEISENBERG_SHOTS,
        q_enc=N_QUBITS,
        R=HEISENBERG_R,
        alpha=HEISENBERG_ALPHA,
        use_tanh_scaling=USE_TANH_SCALING,
        measure_2local_diagonal=MEASURE_2LOCAL_DIAGONAL,
        use_gpu_statevector=True,
        statevector_device="GPU",
        output_root=f"outputs/pqfm/{RUN_LABEL}",
    )
    print("Preparando uma única vez o circuito Heisenberg 13q na GPU...")
    HEISENBERG_PQFM_13Q.fit(
        np.zeros((1, N_PCA_COMPONENTS), dtype=float)
    )
    assert HEISENBERG_PQFM_13Q.theta_info["features_per_block"] == 12
    assert HEISENBERG_PQFM_13Q.theta_info["num_blocks"] == 1
    assert HEISENBERG_PQFM_13Q.theta_info["total_slots"] == 12

    quantum_folds = []
    transform_counter = 0
    transform_total = len(CLASSICAL_BENCHMARK["folds"]) * (INNER_SPLITS + 1)

    for classic_fold in CLASSICAL_BENCHMARK["folds"]:
        outer_fold = classic_fold["outer_fold"]
        inner_quantum = []
        for inner_data in classic_fold["inner_folds"]:
            X_train_pca = inner_data["train_representations"][PCA_REPRESENTATION]
            X_validation_pca = inner_data["validation_representations"][PCA_REPRESENTATION]
            n_train = len(X_train_pca)
            X_all_pca = pd.concat(
                [X_train_pca, X_validation_pca],
                ignore_index=True,
            )
            transform_counter += 1
            print(
                f"[Heisenberg-13q {transform_counter:02d}/{transform_total:02d}] "
                f"outer={outer_fold}/10 | inner={inner_data['inner_fold']}/3 | "
                f"amostras={len(X_all_pca)} | GPU"
            )
            started_at = time.perf_counter()
            Xq_values = HEISENBERG_PQFM_13Q.transform(X_all_pca)
            q_columns = [f"heisenberg_q_{i}" for i in range(Xq_values.shape[1])]
            Xq_all = pd.DataFrame(Xq_values, columns=q_columns)
            inner_quantum.append({
                "inner_fold": inner_data["inner_fold"],
                "X_train_quantum": Xq_all.iloc[:n_train].reset_index(drop=True),
                "X_validation_quantum": Xq_all.iloc[n_train:].reset_index(drop=True),
            })
            print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        X_outer_train_pca = classic_fold["outer_train_representations"][PCA_REPRESENTATION]
        X_outer_test_pca = classic_fold["outer_test_representations"][PCA_REPRESENTATION]
        n_outer_train = len(X_outer_train_pca)
        X_outer_all_pca = pd.concat(
            [X_outer_train_pca, X_outer_test_pca],
            ignore_index=True,
        )
        transform_counter += 1
        print(
            f"[Heisenberg-13q {transform_counter:02d}/{transform_total:02d}] "
            f"outer={outer_fold}/10 | OUTER | "
            f"amostras={len(X_outer_all_pca)} | GPU"
        )
        started_at = time.perf_counter()
        Xq_outer_values = HEISENBERG_PQFM_13Q.transform(X_outer_all_pca)
        q_columns = [
            f"heisenberg_q_{i}" for i in range(Xq_outer_values.shape[1])
        ]
        Xq_outer_all = pd.DataFrame(Xq_outer_values, columns=q_columns)
        print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        quantum_folds.append({
            "classic_fold": classic_fold,
            "inner_quantum": inner_quantum,
            "X_outer_train_quantum": Xq_outer_all.iloc[:n_outer_train].reset_index(drop=True),
            "X_outer_test_quantum": Xq_outer_all.iloc[n_outer_train:].reset_index(drop=True),
        })

    HEISENBERG_PCA_CACHE_13Q_N1000 = {
        "cache_key": HEISENBERG_CACHE_KEY_13Q,
        "config": RUN_LABEL,
        "pca_representation": PCA_REPRESENTATION,
        "n_qubits": N_QUBITS,
        "n_input_features": N_PCA_COMPONENTS,
        "n_blocks": HEISENBERG_PQFM_13Q.theta_info["num_blocks"],
        "n_quantum_features": len(q_columns),
        "folds": quantum_folds,
    }
    print(
        f"Cache concluído: {len(quantum_folds)} outer folds | "
        f"{len(q_columns)} features quânticas por amostra."
    )

Preparando uma única vez o circuito Heisenberg 13q na GPU...
[Heisenberg-13q 01/40] outer=1/10 | inner=1/3 | amostras=50 | GPU
  concluído em 6.6s
[Heisenberg-13q 02/40] outer=1/10 | inner=2/3 | amostras=75 | GPU
  concluído em 10.6s
[Heisenberg-13q 03/40] outer=1/10 | inner=3/3 | amostras=100 | GPU
  concluído em 14.1s
[Heisenberg-13q 04/40] outer=1/10 | OUTER | amostras=190 | GPU
  concluído em 28.7s
[Heisenberg-13q 05/40] outer=2/10 | inner=1/3 | amostras=96 | GPU
  concluído em 15.2s
[Heisenberg-13q 06/40] outer=2/10 | inner=2/3 | amostras=143 | GPU
  concluído em 23.2s
[Heisenberg-13q 07/40] outer=2/10 | inner=3/3 | amostras=190 | GPU
  concluído em 30.6s
[Heisenberg-13q 08/40] outer=2/10 | OUTER | amostras=280 | GPU
  concluído em 46.3s
[Heisenberg-13q 09/40] outer=3/10 | inner=1/3 | amostras=140 | GPU
  concluído em 24.4s
[Heisenberg-13q 10/40] outer=3/10 | inner=2/3 | amostras=210 | GPU
  concluído em 37.4s
[Heisenberg-13q 11/40] outer=3/10 | inner=3/3 | amostras=280 | GPU
  concluído em 49.9s
[Heisenberg-13q 12/40] outer=3/10 | OUTER | amostras=370 | GPU
  concluído em 66.8s
[Heisenberg-13q 13/40] outer=4/10 | inner=1/3 | amostras=186 | GPU
  concluído em 36.1s
[Heisenberg-13q 14/40] outer=4/10 | inner=2/3 | amostras=278 | GPU
  concluído em 51.8s
[Heisenberg-13q 15/40] outer=4/10 | inner=3/3 | amostras=370 | GPU
  concluído em 71.1s
[Heisenberg-13q 16/40] outer=4/10 | OUTER | amostras=460 | GPU
  concluído em 92.0s
[Heisenberg-13q 17/40] outer=5/10 | inner=1/3 | amostras=230 | GPU
  concluído em 48.6s
[Heisenberg-13q 18/40] outer=5/10 | inner=2/3 | amostras=345 | GPU
  concluído em 72.6s
[Heisenberg-13q 19/40] outer=5/10 | inner=3/3 | amostras=460 | GPU
  concluído em 94.7s
[Heisenberg-13q 20/40] outer=5/10 | OUTER | amostras=550 | GPU
  concluído em 115.2s
[Heisenberg-13q 21/40] outer=6/10 | inner=1/3 | amostras=276 | GPU
  concluído em 61.2s
[Heisenberg-13q 22/40] outer=6/10 | inner=2/3 | amostras=413 | GPU
  concluído em 91.6s
[Heisenberg-13q 23/40] outer=6/10 | inner=3/3 | amostras=550 | GPU
  concluído em 122.6s
[Heisenberg-13q 24/40] outer=6/10 | OUTER | amostras=640 | GPU
  concluído em 143.9s
[Heisenberg-13q 25/40] outer=7/10 | inner=1/3 | amostras=320 | GPU
  concluído em 75.9s
[Heisenberg-13q 26/40] outer=7/10 | inner=2/3 | amostras=480 | GPU
  concluído em 113.2s
[Heisenberg-13q 27/40] outer=7/10 | inner=3/3 | amostras=640 | GPU
  concluído em 148.2s
[Heisenberg-13q 28/40] outer=7/10 | OUTER | amostras=730 | GPU
  concluído em 171.3s
[Heisenberg-13q 29/40] outer=8/10 | inner=1/3 | amostras=366 | GPU
  concluído em 93.1s
[Heisenberg-13q 30/40] outer=8/10 | inner=2/3 | amostras=548 | GPU
  concluído em 135.4s
[Heisenberg-13q 31/40] outer=8/10 | inner=3/3 | amostras=730 | GPU
  concluído em 179.7s
[Heisenberg-13q 32/40] outer=8/10 | OUTER | amostras=820 | GPU
  concluído em 211.5s
[Heisenberg-13q 33/40] outer=9/10 | inner=1/3 | amostras=410 | GPU
  concluído em 108.7s
[Heisenberg-13q 34/40] outer=9/10 | inner=2/3 | amostras=615 | GPU
  concluído em 161.7s
[Heisenberg-13q 35/40] outer=9/10 | inner=3/3 | amostras=820 | GPU
  concluído em 217.4s
[Heisenberg-13q 36/40] outer=9/10 | OUTER | amostras=910 | GPU
  concluído em 252.8s
[Heisenberg-13q 37/40] outer=10/10 | inner=1/3 | amostras=456 | GPU
  concluído em 141.4s
[Heisenberg-13q 38/40] outer=10/10 | inner=2/3 | amostras=683 | GPU
  concluído em 209.0s
[Heisenberg-13q 39/40] outer=10/10 | inner=3/3 | amostras=910 | GPU
  concluído em 269.6s
[Heisenberg-13q 40/40] outer=10/10 | OUTER | amostras=1000 | GPU
  concluído em 296.6s
Cache concluído: 10 outer folds | 39 features quânticas por amostra.

In [11]:
# Nested tuning e avaliação. Esta célula não chama a PQFM.
RUN_LABEL = HEISENBERG_PCA_CACHE_13Q_N1000["config"]
PCA_REPRESENTATION = HEISENBERG_PCA_CACHE_13Q_N1000["pca_representation"]
candidates = list(ParameterGrid(CLASSIFIER_GRID))
fold_rows = []
tuning_rows = []

for quantum_fold in HEISENBERG_PCA_CACHE_13Q_N1000["folds"]:
    classic_fold = quantum_fold["classic_fold"]
    outer_fold = classic_fold["outer_fold"]
    print(f"\n[{RUN_LABEL}] tuning/classificação outer fold {outer_fold}/10")
    scores = {
        "quantum_only": {candidate_key(params): [] for params in candidates},
        "hibrida": {candidate_key(params): [] for params in candidates},
    }

    for inner_data, inner_quantum in zip(
        classic_fold["inner_folds"],
        quantum_fold["inner_quantum"],
        strict=True,
    ):
        X_train_classical = inner_data["train_representations"]["all_features"]
        X_validation_classical = inner_data["validation_representations"]["all_features"]
        X_train_quantum = inner_quantum["X_train_quantum"]
        X_validation_quantum = inner_quantum["X_validation_quantum"]
        X_train_hybrid = pd.concat(
            [X_train_classical.reset_index(drop=True), X_train_quantum], axis=1
        )
        X_validation_hybrid = pd.concat(
            [X_validation_classical.reset_index(drop=True), X_validation_quantum], axis=1
        )

        for params in candidates:
            key = candidate_key(params)
            scores["quantum_only"][key].append(
                fit_and_score_classifier(
                    X_train_quantum,
                    inner_data["y_train"],
                    X_validation_quantum,
                    inner_data["y_validation"],
                    params,
                )
            )
            scores["hibrida"][key].append(
                fit_and_score_classifier(
                    X_train_hybrid,
                    inner_data["y_train"],
                    X_validation_hybrid,
                    inner_data["y_validation"],
                    params,
                )
            )

    best_params = {}
    for scenario in ("quantum_only", "hibrida"):
        mean_scores = {
            key: float(np.mean(values))
            for key, values in scores[scenario].items()
        }
        best_key = max(mean_scores, key=mean_scores.get)
        best_params[scenario] = json.loads(best_key)
        for key, values in scores[scenario].items():
            tuning_rows.append({
                "config": RUN_LABEL,
                "outer_fold": outer_fold,
                "scenario": scenario,
                "params": key,
                "mean_inner_average_precision": np.mean(values),
                "std_inner_average_precision": np.std(values, ddof=1),
            })

    fold_rows.append({
        "config": RUN_LABEL,
        "scenario": "classica",
        "outer_fold": outer_fold,
        "n_train": len(classic_fold["train_idx"]),
        "n_test": len(classic_fold["test_idx"]),
        "test_start_position": int(classic_fold["test_idx"][0]),
        "test_end_position": int(classic_fold["test_idx"][-1]),
        "best_params": json.dumps(
            classic_fold["best_params"]["all_features"], sort_keys=True
        ),
        **classic_fold["classic_metrics"]["all_features"],
    })

    X_outer_train_classical = classic_fold["outer_train_representations"]["all_features"]
    X_outer_test_classical = classic_fold["outer_test_representations"]["all_features"]
    X_outer_train_quantum = quantum_fold["X_outer_train_quantum"]
    X_outer_test_quantum = quantum_fold["X_outer_test_quantum"]
    X_outer_train_hybrid = pd.concat(
        [X_outer_train_classical.reset_index(drop=True), X_outer_train_quantum], axis=1
    )
    X_outer_test_hybrid = pd.concat(
        [X_outer_test_classical.reset_index(drop=True), X_outer_test_quantum], axis=1
    )

    for scenario, X_train_rep, X_test_rep in (
        ("quantum_only", X_outer_train_quantum, X_outer_test_quantum),
        ("hibrida", X_outer_train_hybrid, X_outer_test_hybrid),
    ):
        params = best_params[scenario]
        classifier = GradientBoostingClassifier(
            random_state=RANDOM_STATE,
            **params,
        )
        classifier.fit(X_train_rep, classic_fold["y_outer_train"])
        prediction = classifier.predict(X_test_rep)
        probability = classifier.predict_proba(X_test_rep)[:, 1]
        fold_rows.append({
            "config": RUN_LABEL,
            "scenario": scenario,
            "outer_fold": outer_fold,
            "n_train": len(classic_fold["train_idx"]),
            "n_test": len(classic_fold["test_idx"]),
            "test_start_position": int(classic_fold["test_idx"][0]),
            "test_end_position": int(classic_fold["test_idx"][-1]),
            "best_params": json.dumps(params, sort_keys=True),
            **compute_metrics(
                classic_fold["y_outer_test"], prediction, probability
            ),
        })

    checkpoint = {
        "config": RUN_LABEL,
        "fold_results": pd.DataFrame(fold_rows),
        "tuning_results": pd.DataFrame(tuning_rows),
    }
    with open(
        CHECKPOINT_DIR / f"{RUN_LABEL}_fold_{outer_fold:02d}.pkl",
        "wb",
    ) as handle:
        pickle.dump(checkpoint, handle)

HEISENBERG_13Q_PCA12_N1000_RESULT = {
    "config": RUN_LABEL,
    "fold_results": pd.DataFrame(fold_rows),
    "tuning_results": pd.DataFrame(tuning_rows),
}
print(f"Experimento {RUN_LABEL} concluído.")

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 1/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 2/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 3/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 4/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 5/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 6/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 7/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 8/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 9/10

[heisenberg_13q_pca12_n1000_gpu] tuning/classificação outer fold 10/10
Experimento heisenberg_13q_pca12_n1000_gpu concluído.

In [12]:
HEISENBERG_13Q_SUMMARY = summarize_quantum_results(
    HEISENBERG_13Q_PCA12_N1000_RESULT["fold_results"]
)
HEISENBERG_13Q_STATS = quantum_statistical_analysis(
    HEISENBERG_13Q_PCA12_N1000_RESULT["fold_results"],
    title="HEISENBERG 13Q × PCA-12 × N1000 — 10 OUTER FOLDS",
)
display(HEISENBERG_13Q_PCA12_N1000_RESULT["fold_results"])
display(HEISENBERG_13Q_SUMMARY)

================================================================================================
  HEISENBERG 13Q × PCA-12 × N1000 — 10 OUTER FOLDS
================================================================================================
              Comparação     Métrica  Média Base  Média Caso  Δ Médio            IC95% Δ  p-valor                 Status
Clássico vs Quantum-Only     ROC-AUC      0.8107      0.7659  -0.0448  [-0.0880, 0.0134]   0.1055     ↓ Piora (não sig.)
     Clássico vs Híbrido     ROC-AUC      0.8107      0.8150   0.0043  [-0.0351, 0.0585]   0.3750   ↑ Melhora (não sig.)
Clássico vs Quantum-Only      PR-AUC      0.8788      0.8714  -0.0074  [-0.0409, 0.0442]   0.1055     ↓ Piora (não sig.)
     Clássico vs Híbrido      PR-AUC      0.8788      0.8901   0.0112  [-0.0154, 0.0528]   0.3750   ↑ Melhora (não sig.)
Clássico vs Quantum-Only    Accuracy      0.7567      0.7056  -0.0511 [-0.0744, -0.0278]   0.0078 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido    Accuracy      0.7567      0.7478  -0.0089  [-0.0244, 0.0078]   0.3438     ↓ Piora (não sig.)
Clássico vs Quantum-Only   Precision      0.8170      0.8020  -0.0150  [-0.0347, 0.0067]   0.2754     ↓ Piora (não sig.)
     Clássico vs Híbrido   Precision      0.8170      0.8195   0.0025  [-0.0099, 0.0163]   1.0000   ↑ Melhora (não sig.)
Clássico vs Quantum-Only      Recall      0.8030      0.7407  -0.0623 [-0.1120, -0.0050]   0.0488 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido      Recall      0.8030      0.7916  -0.0114  [-0.0401, 0.0203]   0.6875     ↓ Piora (não sig.)
Clássico vs Quantum-Only          F1      0.8081      0.7634  -0.0447 [-0.0703, -0.0199]   0.0137 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido          F1      0.8081      0.8019  -0.0062  [-0.0200, 0.0090]   0.4961     ↓ Piora (não sig.)
Clássico vs Quantum-Only Specificity      0.6689      0.6414  -0.0275  [-0.0948, 0.0436]   0.4961     ↓ Piora (não sig.)
     Clássico vs Híbrido Specificity      0.6689      0.6640  -0.0049  [-0.0495, 0.0414]   1.0000     ↓ Piora (não sig.)

,config,scenario,outer_fold,n_train,n_test,test_start_position,test_end_position,best_params,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1,Specificity
0,heisenberg_13q_pca12_n1000_gpu,classica,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.974085,0.997531,0.944444,0.987342,0.951220,0.968944,0.875000
1,heisenberg_13q_pca12_n1000_gpu,quantum_only,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.913110,0.991237,0.877778,0.973333,0.890244,0.929936,0.750000
2,heisenberg_13q_pca12_n1000_gpu,hibrida,1,100,90,100,189,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.949695,0.994923,0.911111,0.974359,0.926829,0.950000,0.750000
3,heisenberg_13q_pca12_n1000_gpu,classica,2,190,90,190,279,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.870694,0.933492,0.766667,0.839286,0.796610,0.817391,0.709677
4,heisenberg_13q_pca12_n1000_gpu,quantum_only,2,190,90,190,279,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.752324,0.867756,0.666667,0.853659,0.593220,0.700000,0.806452
5,heisenberg_13q_pca12_n1000_gpu,hibrida,2,190,90,190,279,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.863587,0.922880,0.744444,0.875000,0.711864,0.785047,0.806452
6,heisenberg_13q_pca12_n1000_gpu,classica,3,280,90,280,369,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.939001,0.980024,0.866667,0.910448,0.910448,0.910448,0.739130
7,heisenberg_13q_pca12_n1000_gpu,quantum_only,3,280,90,280,369,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.914666,0.969360,0.877778,0.911765,0.925373,0.918519,0.739130
8,heisenberg_13q_pca12_n1000_gpu,hibrida,3,280,90,280,369,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.934458,0.977938,0.877778,0.924242,0.910448,0.917293,0.782609
9,heisenberg_13q_pca12_n1000_gpu,classica,4,370,90,370,459,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.796875,0.924385,0.722222,0.867925,0.718750,0.786325,0.730769
10,heisenberg_13q_pca12_n1000_gpu,quantum_only,4,370,90,370,459,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.769832,0.912062,0.677778,0.888889,0.625000,0.733945,0.807692
11,heisenberg_13q_pca12_n1000_gpu,hibrida,4,370,90,370,459,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.771034,0.916492,0.722222,0.867925,0.718750,0.786325,0.730769
12,heisenberg_13q_pca12_n1000_gpu,classica,5,460,90,460,549,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.490196,0.570284,0.611111,0.637931,0.725490,0.678899,0.461538
13,heisenberg_13q_pca12_n1000_gpu,quantum_only,5,460,90,460,549,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.659125,0.773473,0.611111,0.681818,0.588235,0.631579,0.641026
14,heisenberg_13q_pca12_n1000_gpu,hibrida,5,460,90,460,549,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.713675,0.744860,0.655556,0.685185,0.725490,0.704762,0.564103
15,heisenberg_13q_pca12_n1000_gpu,classica,6,550,90,550,639,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.747500,0.870167,0.677778,0.781818,0.716667,0.747826,0.600000
16,heisenberg_13q_pca12_n1000_gpu,quantum_only,6,550,90,550,639,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.646111,0.823989,0.611111,0.719298,0.683333,0.700855,0.466667
17,heisenberg_13q_pca12_n1000_gpu,hibrida,6,550,90,550,639,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.695556,0.849248,0.655556,0.763636,0.700000,0.730435,0.566667
18,heisenberg_13q_pca12_n1000_gpu,classica,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.720930,0.722875,0.622222,0.632653,0.659574,0.645833,0.581395
19,heisenberg_13q_pca12_n1000_gpu,quantum_only,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.646462,0.660495,0.600000,0.587302,0.787234,0.672727,0.395349
20,heisenberg_13q_pca12_n1000_gpu,hibrida,7,640,90,640,729,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.656606,0.679717,0.622222,0.614035,0.744681,0.673077,0.488372
21,heisenberg_13q_pca12_n1000_gpu,classica,8,730,90,730,819,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.842937,0.899969,0.777778,0.770492,0.886792,0.824561,0.621622
22,heisenberg_13q_pca12_n1000_gpu,quantum_only,8,730,90,730,819,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.851606,0.902596,0.744444,0.741935,0.867925,0.800000,0.567568
23,heisenberg_13q_pca12_n1000_gpu,hibrida,8,730,90,730,819,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.900051,0.941137,0.788889,0.765625,0.924528,0.837607,0.594595
24,heisenberg_13q_pca12_n1000_gpu,classica,9,820,90,820,909,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.870945,0.960140,0.788889,0.903226,0.811594,0.854962,0.714286
25,heisenberg_13q_pca12_n1000_gpu,quantum_only,9,820,90,820,909,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.746722,0.924904,0.700000,0.862069,0.724638,0.787402,0.619048
26,heisenberg_13q_pca12_n1000_gpu,hibrida,9,820,90,820,909,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.847481,0.954768,0.755556,0.885246,0.782609,0.830769,0.666667
27,heisenberg_13q_pca12_n1000_gpu,classica,10,910,90,910,999,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.854155,0.929375,0.788889,0.838710,0.852459,0.845528,0.655172
28,heisenberg_13q_pca12_n1000_gpu,quantum_only,10,910,90,910,999,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.759186,0.887977,0.688889,0.800000,0.721311,0.758621,0.620690
29,heisenberg_13q_pca12_n1000_gpu,hibrida,10,910,90,910,999,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.817976,0.918723,0.744444,0.839286,0.770492,0.803419,0.689655

,config,scenario,metric,n_folds,mean,std,ci95_low,ci95_high
0,heisenberg_13q_pca12_n1000_gpu,classica,ROC-AUC,10,0.810732,0.136739,0.712914,0.908549
1,heisenberg_13q_pca12_n1000_gpu,classica,PR-AUC,10,0.878824,0.132750,0.783860,0.973788
2,heisenberg_13q_pca12_n1000_gpu,classica,Accuracy,10,0.756667,0.103631,0.682534,0.830800
3,heisenberg_13q_pca12_n1000_gpu,classica,Precision,10,0.816983,0.114598,0.735004,0.898962
4,heisenberg_13q_pca12_n1000_gpu,classica,Recall,10,0.802960,0.096739,0.733757,0.872163
5,heisenberg_13q_pca12_n1000_gpu,classica,F1,10,0.808072,0.098562,0.737565,0.878579
6,heisenberg_13q_pca12_n1000_gpu,classica,Specificity,10,0.668859,0.111946,0.588778,0.748940
7,heisenberg_13q_pca12_n1000_gpu,quantum_only,ROC-AUC,10,0.765914,0.100982,0.693676,0.838152
8,heisenberg_13q_pca12_n1000_gpu,quantum_only,PR-AUC,10,0.871385,0.097782,0.801436,0.941334
9,heisenberg_13q_pca12_n1000_gpu,quantum_only,Accuracy,10,0.705556,0.101329,0.633069,0.778042
10,heisenberg_13q_pca12_n1000_gpu,quantum_only,Precision,10,0.802007,0.118425,0.717291,0.886723
11,heisenberg_13q_pca12_n1000_gpu,quantum_only,Recall,10,0.740651,0.123435,0.652351,0.828952
12,heisenberg_13q_pca12_n1000_gpu,quantum_only,F1,10,0.763358,0.098957,0.692569,0.834148
13,heisenberg_13q_pca12_n1000_gpu,quantum_only,Specificity,10,0.641362,0.138922,0.541983,0.740741
14,heisenberg_13q_pca12_n1000_gpu,hibrida,ROC-AUC,10,0.815012,0.102538,0.741660,0.888363
15,heisenberg_13q_pca12_n1000_gpu,hibrida,PR-AUC,10,0.890069,0.102797,0.816532,0.963605
16,heisenberg_13q_pca12_n1000_gpu,hibrida,Accuracy,10,0.747778,0.093558,0.680850,0.814705
17,heisenberg_13q_pca12_n1000_gpu,hibrida,Precision,10,0.819454,0.111241,0.739877,0.899031
18,heisenberg_13q_pca12_n1000_gpu,hibrida,Recall,10,0.791569,0.092638,0.725300,0.857838
19,heisenberg_13q_pca12_n1000_gpu,hibrida,F1,10,0.801873,0.087575,0.739226,0.864521
20,heisenberg_13q_pca12_n1000_gpu,hibrida,Specificity,10,0.663989,0.106456,0.587835,0.740143

# PARTE II — 2.000 amostras

Esta parte usa uma nova amostra estratificada de 2.000 registros. O benchmark clássico contém `all_features`, `pca12`, `pca36`, `shap12` e `shap36`. A camada quântica usa exclusivamente PCA-36.

In [9]:
sampled_2000 = stratified_temporal_sample(df, n_samples=2_000)
X_2000 = sampled_2000[FEATURE_COLS].copy()
y_2000 = sampled_2000[TARGET_COL].astype(int).copy()
OUTER_FOLDS_2000 = make_outer_folds(X_2000)

print(f"Amostra 2.000: {X_2000.shape}")
print(f"Distribuição: {y_2000.value_counts(normalize=True).sort_index().round(4).to_dict()}")
print(f"Período: {sampled_2000['period_start'].min()} → {sampled_2000['period_start'].max()}")
display(describe_nested_sizes(OUTER_FOLDS_2000))

assert min(
    min(sizes)
    for sizes in describe_nested_sizes(OUTER_FOLDS_2000)["inner_train_sizes"]
) >= 37, "A menor janela deve permitir 36 componentes após centralização."

Amostra 2.000: (2000, 36)
Distribuição: {0: 0.3195, 1: 0.6805}
Período: 1946-04-22 04:58:16+00:00 → 2023-03-25 20:57:28+00:00

   outer_fold  outer_train  outer_test inner_train_sizes
0           1          190         181     [49, 96, 143]
1           2          371         181    [95, 187, 279]
2           3          552         181   [138, 276, 414]
3           4          733         181   [184, 367, 550]
4           5          914         181   [230, 458, 686]
5           6         1095         181   [276, 549, 822]
6           7         1276         181   [319, 638, 957]
7           8         1457         181  [365, 729, 1093]
8           9         1638         181  [411, 820, 1229]
9          10         1819         181  [457, 911, 1365]

## Parte II.A — Benchmark clássico, 2.000 amostras

In [10]:
REPRESENTATIONS_2000 = (
    "all_features",
    "pca12",
    "pca36",
    "shap12",
    "shap36",
)
BENCHMARK_KEY_2000 = (
    id(X_2000),
    RANDOM_STATE,
    REPRESENTATIONS_2000,
    tuple((name, tuple(values)) for name, values in sorted(CLASSIFIER_GRID.items())),
)

benchmark_is_current = (
    "CLASSICAL_BENCHMARK_N2000" in globals()
    and CLASSICAL_BENCHMARK_N2000.get("cache_key") == BENCHMARK_KEY_2000
)

if benchmark_is_current:
    print("Benchmark clássico n2000 já existe; reutilizando cache.")
else:
    CLASSICAL_BENCHMARK_N2000 = prepare_classical_benchmark(
        X=X_2000,
        y=y_2000,
        outer_folds=OUTER_FOLDS_2000,
        sample_label="n2000",
        representations=REPRESENTATIONS_2000,
        include_pca36=True,
    )
    CLASSICAL_BENCHMARK_N2000["cache_key"] = BENCHMARK_KEY_2000

[n2000/clássico] outer fold 1/10
[n2000/clássico] outer fold 2/10
[n2000/clássico] outer fold 3/10
[n2000/clássico] outer fold 4/10
[n2000/clássico] outer fold 5/10
[n2000/clássico] outer fold 6/10
[n2000/clássico] outer fold 7/10
[n2000/clássico] outer fold 8/10
[n2000/clássico] outer fold 9/10
[n2000/clássico] outer fold 10/10

In [11]:
CLASSICAL_SUMMARY_N2000 = summarize_classical_results(
    CLASSICAL_BENCHMARK_N2000["fold_results"]
)
CLASSICAL_STATS_N2000 = classical_statistical_analysis(
    CLASSICAL_BENCHMARK_N2000["fold_results"],
    title="BENCHMARK CLÁSSICO — 2.000 AMOSTRAS — 10 OUTER FOLDS",
)

display(CLASSICAL_BENCHMARK_N2000["fold_results"])
display(CLASSICAL_SUMMARY_N2000)

================================================================================================
  BENCHMARK CLÁSSICO — 2.000 AMOSTRAS — 10 OUTER FOLDS
================================================================================================
            Comparação     Métrica  Média Base  Média Caso  Δ Médio            IC95% Δ  p-valor                 Status
 all_features vs pca12     ROC-AUC      0.8437      0.7958  -0.0479 [-0.0723, -0.0223]   0.0195 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca12      PR-AUC      0.9080      0.8844  -0.0236 [-0.0398, -0.0066]   0.0645     ↓ Piora (não sig.)
 all_features vs pca12    Accuracy      0.7707      0.7298  -0.0409  [-0.0906, 0.0011]   0.1641     ↓ Piora (não sig.)
 all_features vs pca12   Precision      0.8308      0.8064  -0.0244 [-0.0491, -0.0010]   0.1602     ↓ Piora (não sig.)
 all_features vs pca12      Recall      0.8123      0.7822  -0.0301  [-0.1143, 0.0412]   0.9219     ↓ Piora (não sig.)
 all_features vs pca12          F1      0.8205      0.7867  -0.0338  [-0.0872, 0.0090]   0.5566     ↓ Piora (não sig.)
 all_features vs pca12 Specificity      0.6785      0.6272  -0.0513  [-0.1274, 0.0165]   0.3750     ↓ Piora (não sig.)
 all_features vs pca36     ROC-AUC      0.8437      0.7969  -0.0469 [-0.0737, -0.0192]   0.0195 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca36      PR-AUC      0.9080      0.8834  -0.0246 [-0.0406, -0.0113]   0.0137 ⚠️ PIORA SIGNIFICATIVA
 all_features vs pca36    Accuracy      0.7707      0.7232  -0.0475 [-0.0912, -0.0027]   0.0840     ↓ Piora (não sig.)
 all_features vs pca36   Precision      0.8308      0.8065  -0.0242  [-0.0493, 0.0005]   0.1309     ↓ Piora (não sig.)
 all_features vs pca36      Recall      0.8123      0.7633  -0.0490  [-0.1184, 0.0080]   0.1641     ↓ Piora (não sig.)
 all_features vs pca36          F1      0.8205      0.7786  -0.0419 [-0.0864, -0.0058]   0.1055     ↓ Piora (não sig.)
 all_features vs pca36 Specificity      0.6785      0.6623  -0.0162  [-0.0872, 0.0505]   0.7695     ↓ Piora (não sig.)
all_features vs shap12     ROC-AUC      0.8437      0.8284  -0.0154  [-0.0327, 0.0007]   0.1602     ↓ Piora (não sig.)
all_features vs shap12      PR-AUC      0.9080      0.8951  -0.0130  [-0.0312, 0.0015]   0.2324     ↓ Piora (não sig.)
all_features vs shap12    Accuracy      0.7707      0.7597  -0.0110  [-0.0276, 0.0044]   0.2031     ↓ Piora (não sig.)
all_features vs shap12   Precision      0.8308      0.8221  -0.0086  [-0.0263, 0.0110]   0.4316     ↓ Piora (não sig.)
all_features vs shap12      Recall      0.8123      0.8065  -0.0058  [-0.0257, 0.0132]   0.7422     ↓ Piora (não sig.)
all_features vs shap12          F1      0.8205      0.8126  -0.0079  [-0.0213, 0.0033]   0.3223     ↓ Piora (não sig.)
all_features vs shap12 Specificity      0.6785      0.6617  -0.0168  [-0.0620, 0.0320]   0.5566     ↓ Piora (não sig.)
all_features vs shap36     ROC-AUC      0.8437      0.8413  -0.0024  [-0.0066, 0.0024]   0.0840     ↓ Piora (não sig.)
all_features vs shap36      PR-AUC      0.9080      0.9064  -0.0017  [-0.0080, 0.0039]   0.6250     ↓ Piora (não sig.)
all_features vs shap36    Accuracy      0.7707      0.7646  -0.0061  [-0.0182, 0.0061]   0.3438     ↓ Piora (não sig.)
all_features vs shap36   Precision      0.8308      0.8278  -0.0029  [-0.0120, 0.0056]   0.6406     ↓ Piora (não sig.)
all_features vs shap36      Recall      0.8123      0.8041  -0.0082  [-0.0239, 0.0069]   0.4688     ↓ Piora (não sig.)
all_features vs shap36          F1      0.8205      0.8147  -0.0058  [-0.0173, 0.0046]   0.3828     ↓ Piora (não sig.)
all_features vs shap36 Specificity      0.6785      0.6760  -0.0025  [-0.0200, 0.0162]   0.6875     ↓ Piora (não sig.)

,sample,representation,outer_fold,n_train,n_test,test_start_position,test_end_position,best_params,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1,Specificity
0,n2000,all_features,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.980402,0.997854,0.966851,0.981595,0.981595,0.981595,0.833333
1,n2000,pca12,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.980743,0.997903,0.955801,0.981366,0.969325,0.975309,0.833333
2,n2000,pca36,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.989264,0.998466,0.972376,1.000000,0.969325,0.984424,1.000000
3,n2000,shap12,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.979721,0.997806,0.961326,0.975610,0.981595,0.978593,0.777778
4,n2000,shap36,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.980743,0.997921,0.966851,0.981595,0.981595,0.981595,0.833333
5,n2000,all_features,2,371,181,371,551,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.921175,0.945414,0.861878,0.913043,0.875000,0.893617,0.836066
6,n2000,pca12,2,371,181,371,551,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.874658,0.912420,0.651934,0.901408,0.533333,0.670157,0.885246
7,n2000,pca36,2,371,181,371,551,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.828825,0.890933,0.662983,0.855422,0.591667,0.699507,0.803279
8,n2000,shap12,2,371,181,371,551,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.910451,0.940618,0.828729,0.880342,0.858333,0.869198,0.770492
9,n2000,shap36,2,371,181,371,551,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.920014,0.946899,0.828729,0.893805,0.841667,0.866953,0.803279
10,n2000,all_features,3,552,181,552,732,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.899880,0.970726,0.801105,0.899225,0.834532,0.865672,0.690476
11,n2000,pca12,3,552,181,552,732,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.928743,0.978853,0.861878,0.919118,0.899281,0.909091,0.738095
12,n2000,pca36,3,552,181,552,732,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.933282,0.980104,0.883978,0.933824,0.913669,0.923636,0.785714
13,n2000,shap12,3,552,181,552,732,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.901764,0.971307,0.790055,0.917355,0.798561,0.853846,0.761905
14,n2000,shap36,3,552,181,552,732,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.895427,0.969509,0.801105,0.899225,0.834532,0.865672,0.690476
15,n2000,all_features,4,733,181,733,913,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.840548,0.937164,0.762431,0.854701,0.793651,0.823045,0.690909
16,n2000,pca12,4,733,181,733,913,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.812915,0.914770,0.801105,0.881356,0.825397,0.852459,0.745455
17,n2000,pca36,4,733,181,733,913,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.838384,0.929647,0.773481,0.876106,0.785714,0.828452,0.745455
18,n2000,shap12,4,733,181,733,913,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.866955,0.944012,0.784530,0.853659,0.833333,0.843373,0.672727
19,n2000,shap36,4,733,181,733,913,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.834416,0.913365,0.740331,0.869159,0.738095,0.798283,0.745455
20,n2000,all_features,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.780769,0.871676,0.734807,0.793103,0.793103,0.793103,0.630769
21,n2000,pca12,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.681233,0.828853,0.602210,0.729167,0.603448,0.660377,0.600000
22,n2000,pca36,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.708422,0.843816,0.635359,0.760417,0.629310,0.688679,0.646154
23,n2000,shap12,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.790782,0.887410,0.723757,0.784483,0.784483,0.784483,0.615385
24,n2000,shap36,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.778316,0.862254,0.740331,0.800000,0.793103,0.796537,0.646154
25,n2000,all_features,6,1095,181,1095,1275,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.739978,0.871282,0.635359,0.760000,0.644068,0.697248,0.619048
26,n2000,pca12,6,1095,181,1095,1275,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.642521,0.796921,0.635359,0.706349,0.754237,0.729508,0.412698
27,n2000,pca36,6,1095,181,1095,1275,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.627388,0.797439,0.596685,0.727273,0.610169,0.663594,0.571429
28,n2000,shap12,6,1095,181,1095,1275,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.673258,0.828599,0.629834,0.733945,0.677966,0.704846,0.539683
29,n2000,shap36,6,1095,181,1095,1275,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.733925,0.867932,0.629834,0.747573,0.652542,0.696833,0.587302
30,n2000,all_features,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.717705,0.690054,0.679558,0.656863,0.744444,0.697917,0.615385
31,n2000,pca12,7,1276,181,1276,1456,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.694261,0.717791,0.668508,0.631579,0.800000,0.705882,0.538462
32,n2000,pca36,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.663492,0.676506,0.591160,0.564516,0.777778,0.654206,0.406593
33,n2000,shap12,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.660317,0.608210,0.613260,0.592593,0.711111,0.646465,0.516484
34,n2000,shap36,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.701648,0.704793,0.646409,0.630000,0.700000,0.663158,0.593407
35,n2000,all_features,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.840053,0.915065,0.729282,0.779661,0.800000,0.789700,0.606061
36,n2000,pca12,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.745389,0.867226,0.657459,0.696296,0.817391,0.752000,0.378788
37,n2000,pca36,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.762978,0.877790,0.657459,0.705426,0.791304,0.745902,0.424242
38,n2000,shap12,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.825296,0.913321,0.756906,0.814159,0.800000,0.807018,0.681818
39,n2000,shap36,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.855072,0.921477,0.751381,0.796610,0.817391,0.806867,0.636364
40,n2000,all_features,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.838029,0.937928,0.751381,0.833333,0.813953,0.823529,0.596154
41,n2000,pca12,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.781008,0.912428,0.729282,0.850877,0.751938,0.798354,0.673077
42,n2000,pca36,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.788014,0.916900,0.707182,0.845455,0.720930,0.778243,0.673077
43,n2000,shap12,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.821407,0.929596,0.745856,0.873874,0.751938,0.808333,0.730769
44,n2000,shap36,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.835495,0.937136,0.734807,0.818898,0.806202,0.812500,0.557692
45,n2000,all_features,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.878788,0.943179,0.784530,0.836066,0.842975,0.839506,0.666667
46,n2000,pca12,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.816873,0.917050,0.734807,0.766423,0.867769,0.813953,0.466667
47,n2000,pca36,10,1819,181,1819,1999,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.828650,0.922564,0.751381,0.796875,0.842975,0.819277,0.566667
48,n2000,shap12,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.853719,0.929891,0.762431,0.795455,0.867769,0.830040,0.550000
49,n2000,shap36,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.877824,0.942393,0.806630,0.841270,0.876033,0.858300,0.666667

,sample,representation,metric,n_folds,mean,std,ci95_low,ci95_high
0,n2000,all_features,ROC-AUC,10,0.843733,0.081463,0.785458,0.902008
1,n2000,all_features,PR-AUC,10,0.908034,0.086030,0.846492,0.969576
2,n2000,all_features,Accuracy,10,0.770718,0.093079,0.704133,0.837303
3,n2000,all_features,Precision,10,0.830759,0.090734,0.765852,0.895666
4,n2000,all_features,Recall,10,0.812332,0.086797,0.750241,0.874423
5,n2000,all_features,F1,10,0.820493,0.085396,0.759405,0.881582
6,n2000,all_features,Specificity,10,0.678487,0.088858,0.614921,0.742052
7,n2000,pca12,ROC-AUC,10,0.795834,0.109810,0.717281,0.874388
8,n2000,pca12,PR-AUC,10,0.884422,0.084429,0.824024,0.944819
9,n2000,pca12,Accuracy,10,0.729834,0.112488,0.649365,0.810303
10,n2000,pca12,Precision,10,0.806394,0.115566,0.723723,0.889065
11,n2000,pca12,Recall,10,0.782212,0.131255,0.688318,0.876106
12,n2000,pca12,F1,10,0.786709,0.103442,0.712711,0.860707
13,n2000,pca12,Specificity,10,0.627182,0.176248,0.501102,0.753262
14,n2000,pca36,ROC-AUC,10,0.796870,0.113010,0.716027,0.877713
15,n2000,pca36,PR-AUC,10,0.883416,0.093830,0.816295,0.950538
16,n2000,pca36,Accuracy,10,0.723204,0.124998,0.633786,0.812623
17,n2000,pca36,Precision,10,0.806531,0.124577,0.717414,0.895648
18,n2000,pca36,Recall,10,0.763284,0.127173,0.672310,0.854258
19,n2000,pca36,F1,10,0.778592,0.111380,0.698915,0.858269
20,n2000,pca36,Specificity,10,0.662261,0.181322,0.532551,0.791971
21,n2000,shap12,ROC-AUC,10,0.828367,0.100518,0.756461,0.900273
22,n2000,shap12,PR-AUC,10,0.895077,0.110725,0.815869,0.974285
23,n2000,shap12,Accuracy,10,0.759669,0.098186,0.689430,0.829907
24,n2000,shap12,Precision,10,0.822147,0.106636,0.745865,0.898430
25,n2000,shap12,Recall,10,0.806509,0.086285,0.744784,0.868234
26,n2000,shap12,F1,10,0.812619,0.090530,0.747858,0.877381
27,n2000,shap12,Specificity,10,0.661704,0.100690,0.589675,0.733733
28,n2000,shap36,ROC-AUC,10,0.841288,0.085097,0.780413,0.902163
29,n2000,shap36,PR-AUC,10,0.906368,0.082050,0.847673,0.965063
30,n2000,shap36,Accuracy,10,0.764641,0.095736,0.696156,0.833126
31,n2000,shap36,Precision,10,0.827813,0.095678,0.759369,0.896258
32,n2000,shap36,Recall,10,0.804116,0.092785,0.737742,0.870490
33,n2000,shap36,F1,10,0.814670,0.089819,0.750417,0.878922
34,n2000,shap36,Specificity,10,0.676013,0.092629,0.609750,0.742276

## Parte II.B — Heisenberg 19q × PCA-36, GPU

Dezenove qubits formam uma cadeia com 18 arestas por bloco. As 36 componentes PCA ocupam exatamente dois blocos.

In [16]:
# ── CONFIGURAÇÃO EDITÁVEL DESTA CÉLULA ──────────────────────────────
RUN_LABEL = "heisenberg_19q_pca36_n2000_gpu"
N_QUBITS = 19
N_PCA_COMPONENTS = 36
HEISENBERG_R = 2
HEISENBERG_ALPHA = 0.1
HEISENBERG_SHOTS = SHOTS
USE_TANH_SCALING = True
MEASURE_2LOCAL_DIAGONAL = False
CLASSICAL_BENCHMARK = CLASSICAL_BENCHMARK_N2000
PCA_REPRESENTATION = "pca36"
# ────────────────────────────────────────────────────────────────────

HEISENBERG_CACHE_KEY_19Q = (
    RUN_LABEL,
    id(CLASSICAL_BENCHMARK),
    RANDOM_STATE,
    N_QUBITS,
    N_PCA_COMPONENTS,
    HEISENBERG_R,
    HEISENBERG_ALPHA,
    HEISENBERG_SHOTS,
    USE_TANH_SCALING,
    MEASURE_2LOCAL_DIAGONAL,
)
cache_is_current = (
    "HEISENBERG_PCA_CACHE_19Q_N2000" in globals()
    and HEISENBERG_PCA_CACHE_19Q_N2000.get("cache_key")
    == HEISENBERG_CACHE_KEY_19Q
)

if cache_is_current:
    print("Cache Heisenberg 19q/PCA-36/n2000 já existe; reutilizando.")
else:
    HEISENBERG_PQFM_19Q = HeisenbergProjectiveQFM(
        name_file=RUN_LABEL,
        seed=RANDOM_STATE,
        ideal=True,
        simulation=True,
        fakebackend=False,
        shots=HEISENBERG_SHOTS,
        q_enc=N_QUBITS,
        R=HEISENBERG_R,
        alpha=HEISENBERG_ALPHA,
        use_tanh_scaling=USE_TANH_SCALING,
        measure_2local_diagonal=MEASURE_2LOCAL_DIAGONAL,
        use_gpu_statevector=True,
        statevector_device="GPU",
        output_root=f"outputs/pqfm/{RUN_LABEL}",
    )
    print("Preparando uma única vez o circuito Heisenberg 19q na GPU...")
    HEISENBERG_PQFM_19Q.fit(
        np.zeros((1, N_PCA_COMPONENTS), dtype=float)
    )
    assert HEISENBERG_PQFM_19Q.theta_info["features_per_block"] == 18
    assert HEISENBERG_PQFM_19Q.theta_info["num_blocks"] == 2
    assert HEISENBERG_PQFM_19Q.theta_info["total_slots"] == 36

    quantum_folds = []
    transform_counter = 0
    transform_total = len(CLASSICAL_BENCHMARK["folds"]) * (INNER_SPLITS + 1)

    for classic_fold in CLASSICAL_BENCHMARK["folds"]:
        outer_fold = classic_fold["outer_fold"]
        inner_quantum = []
        for inner_data in classic_fold["inner_folds"]:
            X_train_pca = inner_data["train_representations"][PCA_REPRESENTATION]
            X_validation_pca = inner_data["validation_representations"][PCA_REPRESENTATION]
            n_train = len(X_train_pca)
            X_all_pca = pd.concat(
                [X_train_pca, X_validation_pca],
                ignore_index=True,
            )
            transform_counter += 1
            print(
                f"[Heisenberg-19q {transform_counter:02d}/{transform_total:02d}] "
                f"outer={outer_fold}/10 | inner={inner_data['inner_fold']}/3 | "
                f"amostras={len(X_all_pca)} | GPU"
            )
            started_at = time.perf_counter()
            Xq_values = HEISENBERG_PQFM_19Q.transform(X_all_pca)
            q_columns = [f"heisenberg_q_{i}" for i in range(Xq_values.shape[1])]
            Xq_all = pd.DataFrame(Xq_values, columns=q_columns)
            inner_quantum.append({
                "inner_fold": inner_data["inner_fold"],
                "X_train_quantum": Xq_all.iloc[:n_train].reset_index(drop=True),
                "X_validation_quantum": Xq_all.iloc[n_train:].reset_index(drop=True),
            })
            print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        X_outer_train_pca = classic_fold["outer_train_representations"][PCA_REPRESENTATION]
        X_outer_test_pca = classic_fold["outer_test_representations"][PCA_REPRESENTATION]
        n_outer_train = len(X_outer_train_pca)
        X_outer_all_pca = pd.concat(
            [X_outer_train_pca, X_outer_test_pca],
            ignore_index=True,
        )
        transform_counter += 1
        print(
            f"[Heisenberg-19q {transform_counter:02d}/{transform_total:02d}] "
            f"outer={outer_fold}/10 | OUTER | "
            f"amostras={len(X_outer_all_pca)} | GPU"
        )
        started_at = time.perf_counter()
        Xq_outer_values = HEISENBERG_PQFM_19Q.transform(X_outer_all_pca)
        q_columns = [
            f"heisenberg_q_{i}" for i in range(Xq_outer_values.shape[1])
        ]
        Xq_outer_all = pd.DataFrame(Xq_outer_values, columns=q_columns)
        print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        quantum_folds.append({
            "classic_fold": classic_fold,
            "inner_quantum": inner_quantum,
            "X_outer_train_quantum": Xq_outer_all.iloc[:n_outer_train].reset_index(drop=True),
            "X_outer_test_quantum": Xq_outer_all.iloc[n_outer_train:].reset_index(drop=True),
        })

    HEISENBERG_PCA_CACHE_19Q_N2000 = {
        "cache_key": HEISENBERG_CACHE_KEY_19Q,
        "config": RUN_LABEL,
        "pca_representation": PCA_REPRESENTATION,
        "n_qubits": N_QUBITS,
        "n_input_features": N_PCA_COMPONENTS,
        "n_blocks": HEISENBERG_PQFM_19Q.theta_info["num_blocks"],
        "n_quantum_features": len(q_columns),
        "folds": quantum_folds,
    }
    print(
        f"Cache concluído: {len(quantum_folds)} outer folds | "
        f"{len(q_columns)} features quânticas por amostra."
    )

Preparando uma única vez o circuito Heisenberg 19q na GPU...
[Heisenberg-19q 01/40] outer=1/10 | inner=1/3 | amostras=96 | GPU
  concluído em 36.7s
[Heisenberg-19q 02/40] outer=1/10 | inner=2/3 | amostras=143 | GPU
  concluído em 55.1s
[Heisenberg-19q 03/40] outer=1/10 | inner=3/3 | amostras=190 | GPU
  concluído em 72.7s
[Heisenberg-19q 04/40] outer=1/10 | OUTER | amostras=371 | GPU
  concluído em 146.4s
[Heisenberg-19q 05/40] outer=2/10 | inner=1/3 | amostras=187 | GPU
  concluído em 76.6s
[Heisenberg-19q 06/40] outer=2/10 | inner=2/3 | amostras=279 | GPU
  concluído em 116.8s
[Heisenberg-19q 07/40] outer=2/10 | inner=3/3 | amostras=371 | GPU
  concluído em 153.8s
[Heisenberg-19q 08/40] outer=2/10 | OUTER | amostras=552 | GPU
  concluído em 231.0s
[Heisenberg-19q 09/40] outer=3/10 | inner=1/3 | amostras=276 | GPU
  concluído em 129.2s
[Heisenberg-19q 10/40] outer=3/10 | inner=2/3 | amostras=414 | GPU
  concluído em 183.0s
[Heisenberg-19q 11/40] outer=3/10 | inner=3/3 | amostras=552 | GPU
  concluído em 248.3s
[Heisenberg-19q 12/40] outer=3/10 | OUTER | amostras=733 | GPU
  concluído em 348.3s
[Heisenberg-19q 13/40] outer=4/10 | inner=1/3 | amostras=367 | GPU
  concluído em 195.5s
[Heisenberg-19q 14/40] outer=4/10 | inner=2/3 | amostras=550 | GPU
  concluído em 296.8s
[Heisenberg-19q 15/40] outer=4/10 | inner=3/3 | amostras=733 | GPU
  concluído em 399.3s
[Heisenberg-19q 16/40] outer=4/10 | OUTER | amostras=914 | GPU
  concluído em 504.6s
[Heisenberg-19q 17/40] outer=5/10 | inner=1/3 | amostras=458 | GPU
  concluído em 270.4s
[Heisenberg-19q 18/40] outer=5/10 | inner=2/3 | amostras=686 | GPU
  concluído em 409.3s
[Heisenberg-19q 19/40] outer=5/10 | inner=3/3 | amostras=914 | GPU
  concluído em 548.5s
[Heisenberg-19q 20/40] outer=5/10 | OUTER | amostras=1095 | GPU
  concluído em 664.5s
[Heisenberg-19q 21/40] outer=6/10 | inner=1/3 | amostras=549 | GPU
  concluído em 359.3s
[Heisenberg-19q 22/40] outer=6/10 | inner=2/3 | amostras=822 | GPU
  concluído em 544.2s
[Heisenberg-19q 23/40] outer=6/10 | inner=3/3 | amostras=1095 | GPU
  concluído em 724.6s
[Heisenberg-19q 24/40] outer=6/10 | OUTER | amostras=1276 | GPU
  concluído em 875.3s
[Heisenberg-19q 25/40] outer=7/10 | inner=1/3 | amostras=638 | GPU
  concluído em 458.1s
[Heisenberg-19q 26/40] outer=7/10 | inner=2/3 | amostras=957 | GPU
  concluído em 693.7s
[Heisenberg-19q 27/40] outer=7/10 | inner=3/3 | amostras=1276 | GPU
  concluído em 911.9s
[Heisenberg-19q 28/40] outer=7/10 | OUTER | amostras=1457 | GPU
  concluído em 1063.4s
[Heisenberg-19q 29/40] outer=8/10 | inner=1/3 | amostras=729 | GPU
  concluído em 562.5s
[Heisenberg-19q 30/40] outer=8/10 | inner=2/3 | amostras=1093 | GPU
  concluído em 848.8s
[Heisenberg-19q 31/40] outer=8/10 | inner=3/3 | amostras=1457 | GPU
  concluído em 1090.9s
[Heisenberg-19q 32/40] outer=8/10 | OUTER | amostras=1638 | GPU
  concluído em 1286.9s
[Heisenberg-19q 33/40] outer=9/10 | inner=1/3 | amostras=820 | GPU
  concluído em 688.3s
[Heisenberg-19q 34/40] outer=9/10 | inner=2/3 | amostras=1229 | GPU
  concluído em 1044.6s
[Heisenberg-19q 35/40] outer=9/10 | inner=3/3 | amostras=1638 | GPU
  concluído em 1340.3s
[Heisenberg-19q 36/40] outer=9/10 | OUTER | amostras=1819 | GPU
  concluído em 1563.3s
[Heisenberg-19q 37/40] outer=10/10 | inner=1/3 | amostras=911 | GPU
  concluído em 826.8s
[Heisenberg-19q 38/40] outer=10/10 | inner=2/3 | amostras=1365 | GPU
  concluído em 1228.7s
[Heisenberg-19q 39/40] outer=10/10 | inner=3/3 | amostras=1819 | GPU
  concluído em 1639.9s
[Heisenberg-19q 40/40] outer=10/10 | OUTER | amostras=2000 | GPU
  concluído em 1841.7s
Cache concluído: 10 outer folds | 57 features quânticas por amostra.

In [17]:
# Nested tuning e avaliação. Esta célula não chama a PQFM.
RUN_LABEL = HEISENBERG_PCA_CACHE_19Q_N2000["config"]
PCA_REPRESENTATION = HEISENBERG_PCA_CACHE_19Q_N2000["pca_representation"]
candidates = list(ParameterGrid(CLASSIFIER_GRID))
fold_rows = []
tuning_rows = []

for quantum_fold in HEISENBERG_PCA_CACHE_19Q_N2000["folds"]:
    classic_fold = quantum_fold["classic_fold"]
    outer_fold = classic_fold["outer_fold"]
    print(f"\n[{RUN_LABEL}] tuning/classificação outer fold {outer_fold}/10")
    scores = {
        "quantum_only": {candidate_key(params): [] for params in candidates},
        "hibrida": {candidate_key(params): [] for params in candidates},
    }

    for inner_data, inner_quantum in zip(
        classic_fold["inner_folds"],
        quantum_fold["inner_quantum"],
        strict=True,
    ):
        X_train_classical = inner_data["train_representations"]["all_features"]
        X_validation_classical = inner_data["validation_representations"]["all_features"]
        X_train_quantum = inner_quantum["X_train_quantum"]
        X_validation_quantum = inner_quantum["X_validation_quantum"]
        X_train_hybrid = pd.concat(
            [X_train_classical.reset_index(drop=True), X_train_quantum], axis=1
        )
        X_validation_hybrid = pd.concat(
            [X_validation_classical.reset_index(drop=True), X_validation_quantum], axis=1
        )

        for params in candidates:
            key = candidate_key(params)
            scores["quantum_only"][key].append(
                fit_and_score_classifier(
                    X_train_quantum,
                    inner_data["y_train"],
                    X_validation_quantum,
                    inner_data["y_validation"],
                    params,
                )
            )
            scores["hibrida"][key].append(
                fit_and_score_classifier(
                    X_train_hybrid,
                    inner_data["y_train"],
                    X_validation_hybrid,
                    inner_data["y_validation"],
                    params,
                )
            )

    best_params = {}
    for scenario in ("quantum_only", "hibrida"):
        mean_scores = {
            key: float(np.mean(values))
            for key, values in scores[scenario].items()
        }
        best_key = max(mean_scores, key=mean_scores.get)
        best_params[scenario] = json.loads(best_key)
        for key, values in scores[scenario].items():
            tuning_rows.append({
                "config": RUN_LABEL,
                "outer_fold": outer_fold,
                "scenario": scenario,
                "params": key,
                "mean_inner_average_precision": np.mean(values),
                "std_inner_average_precision": np.std(values, ddof=1),
            })

    fold_rows.append({
        "config": RUN_LABEL,
        "scenario": "classica",
        "outer_fold": outer_fold,
        "n_train": len(classic_fold["train_idx"]),
        "n_test": len(classic_fold["test_idx"]),
        "test_start_position": int(classic_fold["test_idx"][0]),
        "test_end_position": int(classic_fold["test_idx"][-1]),
        "best_params": json.dumps(
            classic_fold["best_params"]["all_features"], sort_keys=True
        ),
        **classic_fold["classic_metrics"]["all_features"],
    })

    X_outer_train_classical = classic_fold["outer_train_representations"]["all_features"]
    X_outer_test_classical = classic_fold["outer_test_representations"]["all_features"]
    X_outer_train_quantum = quantum_fold["X_outer_train_quantum"]
    X_outer_test_quantum = quantum_fold["X_outer_test_quantum"]
    X_outer_train_hybrid = pd.concat(
        [X_outer_train_classical.reset_index(drop=True), X_outer_train_quantum], axis=1
    )
    X_outer_test_hybrid = pd.concat(
        [X_outer_test_classical.reset_index(drop=True), X_outer_test_quantum], axis=1
    )

    for scenario, X_train_rep, X_test_rep in (
        ("quantum_only", X_outer_train_quantum, X_outer_test_quantum),
        ("hibrida", X_outer_train_hybrid, X_outer_test_hybrid),
    ):
        params = best_params[scenario]
        classifier = GradientBoostingClassifier(
            random_state=RANDOM_STATE,
            **params,
        )
        classifier.fit(X_train_rep, classic_fold["y_outer_train"])
        prediction = classifier.predict(X_test_rep)
        probability = classifier.predict_proba(X_test_rep)[:, 1]
        fold_rows.append({
            "config": RUN_LABEL,
            "scenario": scenario,
            "outer_fold": outer_fold,
            "n_train": len(classic_fold["train_idx"]),
            "n_test": len(classic_fold["test_idx"]),
            "test_start_position": int(classic_fold["test_idx"][0]),
            "test_end_position": int(classic_fold["test_idx"][-1]),
            "best_params": json.dumps(params, sort_keys=True),
            **compute_metrics(
                classic_fold["y_outer_test"], prediction, probability
            ),
        })

    checkpoint = {
        "config": RUN_LABEL,
        "fold_results": pd.DataFrame(fold_rows),
        "tuning_results": pd.DataFrame(tuning_rows),
    }
    with open(
        CHECKPOINT_DIR / f"{RUN_LABEL}_fold_{outer_fold:02d}.pkl",
        "wb",
    ) as handle:
        pickle.dump(checkpoint, handle)

HEISENBERG_19Q_PCA36_N2000_RESULT = {
    "config": RUN_LABEL,
    "fold_results": pd.DataFrame(fold_rows),
    "tuning_results": pd.DataFrame(tuning_rows),
}
print(f"Experimento {RUN_LABEL} concluído.")

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 1/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 2/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 3/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 4/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 5/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 6/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 7/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 8/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 9/10

[heisenberg_19q_pca36_n2000_gpu] tuning/classificação outer fold 10/10
Experimento heisenberg_19q_pca36_n2000_gpu concluído.

In [18]:
HEISENBERG_19Q_SUMMARY = summarize_quantum_results(
    HEISENBERG_19Q_PCA36_N2000_RESULT["fold_results"]
)
HEISENBERG_19Q_STATS = quantum_statistical_analysis(
    HEISENBERG_19Q_PCA36_N2000_RESULT["fold_results"],
    title="HEISENBERG 19Q × PCA-36 × N2000 — 10 OUTER FOLDS",
)
display(HEISENBERG_19Q_PCA36_N2000_RESULT["fold_results"])
display(HEISENBERG_19Q_SUMMARY)

================================================================================================
  HEISENBERG 19Q × PCA-36 × N2000 — 10 OUTER FOLDS
================================================================================================
              Comparação     Métrica  Média Base  Média Caso  Δ Médio            IC95% Δ  p-valor                 Status
Clássico vs Quantum-Only     ROC-AUC      0.8437      0.7785  -0.0652 [-0.1053, -0.0314]   0.0098 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido     ROC-AUC      0.8437      0.8423  -0.0015  [-0.0152, 0.0126]   0.8457     ↓ Piora (não sig.)
Clássico vs Quantum-Only      PR-AUC      0.9080      0.8781  -0.0300 [-0.0491, -0.0137]   0.0098 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido      PR-AUC      0.9080      0.9061  -0.0019  [-0.0097, 0.0057]   0.6953     ↓ Piora (não sig.)
Clássico vs Quantum-Only    Accuracy      0.7707      0.7066  -0.0641 [-0.1144, -0.0221]   0.0156 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido    Accuracy      0.7707      0.7801   0.0094  [-0.0061, 0.0249]   0.3164   ↑ Melhora (não sig.)
Clássico vs Quantum-Only   Precision      0.8308      0.7924  -0.0384 [-0.0698, -0.0112]   0.0840     ↓ Piora (não sig.)
     Clássico vs Híbrido   Precision      0.8308      0.8435   0.0127  [-0.0041, 0.0283]   0.1309   ↑ Melhora (não sig.)
Clássico vs Quantum-Only      Recall      0.8123      0.7491  -0.0632  [-0.1441, 0.0012]   0.2324     ↓ Piora (não sig.)
     Clássico vs Híbrido      Recall      0.8123      0.8117  -0.0006  [-0.0192, 0.0189]   0.9219     ↓ Piora (não sig.)
Clássico vs Quantum-Only          F1      0.8205      0.7630  -0.0575 [-0.1106, -0.0160]   0.0137 ⚠️ PIORA SIGNIFICATIVA
     Clássico vs Híbrido          F1      0.8205      0.8260   0.0055  [-0.0076, 0.0179]   0.5566   ↑ Melhora (não sig.)
Clássico vs Quantum-Only Specificity      0.6785      0.6077  -0.0708  [-0.1417, 0.0050]   0.1309     ↓ Piora (não sig.)
     Clássico vs Híbrido Specificity      0.6785      0.7205   0.0420  [-0.0050, 0.0843]   0.1309   ↑ Melhora (não sig.)

,config,scenario,outer_fold,n_train,n_test,test_start_position,test_end_position,best_params,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1,Specificity
0,heisenberg_19q_pca36_n2000_gpu,classica,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.980402,0.997854,0.966851,0.981595,0.981595,0.981595,0.833333
1,heisenberg_19q_pca36_n2000_gpu,quantum_only,1,190,181,190,370,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.984663,0.998375,0.955801,0.958580,0.993865,0.975904,0.611111
2,heisenberg_19q_pca36_n2000_gpu,hibrida,1,190,181,190,370,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.982618,0.997982,0.966851,0.993711,0.969325,0.981366,0.944444
3,heisenberg_19q_pca36_n2000_gpu,classica,2,371,181,371,551,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.921175,0.945414,0.861878,0.913043,0.875000,0.893617,0.836066
4,heisenberg_19q_pca36_n2000_gpu,quantum_only,2,371,181,371,551,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.714208,0.855400,0.624309,0.788889,0.591667,0.676190,0.688525
5,heisenberg_19q_pca36_n2000_gpu,hibrida,2,371,181,371,551,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.898087,0.937670,0.823204,0.866667,0.866667,0.866667,0.737705
6,heisenberg_19q_pca36_n2000_gpu,classica,3,552,181,552,732,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.899880,0.970726,0.801105,0.899225,0.834532,0.865672,0.690476
7,heisenberg_19q_pca36_n2000_gpu,quantum_only,3,552,181,552,732,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.910415,0.974681,0.823204,0.914729,0.848921,0.880597,0.738095
8,heisenberg_19q_pca36_n2000_gpu,hibrida,3,552,181,552,732,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.905447,0.972536,0.812155,0.941176,0.805755,0.868217,0.833333
9,heisenberg_19q_pca36_n2000_gpu,classica,4,733,181,733,913,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.840548,0.937164,0.762431,0.854701,0.793651,0.823045,0.690909
10,heisenberg_19q_pca36_n2000_gpu,quantum_only,4,733,181,733,913,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.829726,0.928685,0.751381,0.864865,0.761905,0.810127,0.727273
11,heisenberg_19q_pca36_n2000_gpu,hibrida,4,733,181,733,913,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.836508,0.915995,0.745856,0.857143,0.761905,0.806723,0.709091
12,heisenberg_19q_pca36_n2000_gpu,classica,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.780769,0.871676,0.734807,0.793103,0.793103,0.793103,0.630769
13,heisenberg_19q_pca36_n2000_gpu,quantum_only,5,914,181,914,1094,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.688594,0.831582,0.596685,0.794521,0.500000,0.613757,0.769231
14,heisenberg_19q_pca36_n2000_gpu,hibrida,5,914,181,914,1094,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.802653,0.889754,0.740331,0.822430,0.758621,0.789238,0.707692
15,heisenberg_19q_pca36_n2000_gpu,classica,6,1095,181,1095,1275,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.739978,0.871282,0.635359,0.760000,0.644068,0.697248,0.619048
16,heisenberg_19q_pca36_n2000_gpu,quantum_only,6,1095,181,1095,1275,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.615954,0.798190,0.546961,0.680000,0.576271,0.623853,0.492063
17,heisenberg_19q_pca36_n2000_gpu,hibrida,6,1095,181,1095,1275,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.695857,0.851942,0.662983,0.776699,0.677966,0.723982,0.634921
18,heisenberg_19q_pca36_n2000_gpu,classica,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 5, ""n_est...",0.717705,0.690054,0.679558,0.656863,0.744444,0.697917,0.615385
19,heisenberg_19q_pca36_n2000_gpu,quantum_only,7,1276,181,1276,1456,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.652503,0.674724,0.591160,0.565574,0.766667,0.650943,0.417582
20,heisenberg_19q_pca36_n2000_gpu,hibrida,7,1276,181,1276,1456,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.694139,0.676555,0.674033,0.659794,0.711111,0.684492,0.637363
21,heisenberg_19q_pca36_n2000_gpu,classica,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.840053,0.915065,0.729282,0.779661,0.800000,0.789700,0.606061
22,heisenberg_19q_pca36_n2000_gpu,quantum_only,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.778788,0.887282,0.707182,0.746032,0.817391,0.780083,0.515152
23,heisenberg_19q_pca36_n2000_gpu,hibrida,8,1457,181,1457,1637,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.861001,0.928768,0.773481,0.803279,0.852174,0.827004,0.636364
24,heisenberg_19q_pca36_n2000_gpu,classica,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.838029,0.937928,0.751381,0.833333,0.813953,0.823529,0.596154
25,heisenberg_19q_pca36_n2000_gpu,quantum_only,9,1638,181,1638,1818,"{""learning_rate"": 0.1, ""max_depth"": 3, ""n_esti...",0.780262,0.910056,0.734807,0.840336,0.775194,0.806452,0.634615
26,heisenberg_19q_pca36_n2000_gpu,hibrida,9,1638,181,1638,1818,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.872093,0.949026,0.801105,0.884298,0.829457,0.856000,0.730769
27,heisenberg_19q_pca36_n2000_gpu,classica,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.878788,0.943179,0.784530,0.836066,0.842975,0.839506,0.666667
28,heisenberg_19q_pca36_n2000_gpu,quantum_only,10,1819,181,1819,1999,"{""learning_rate"": 0.1, ""max_depth"": 5, ""n_esti...",0.830165,0.921616,0.734807,0.770370,0.859504,0.812500,0.483333
29,heisenberg_19q_pca36_n2000_gpu,hibrida,10,1819,181,1819,1999,"{""learning_rate"": 0.05, ""max_depth"": 3, ""n_est...",0.874380,0.940921,0.801105,0.829457,0.884298,0.856000,0.633333

,config,scenario,metric,n_folds,mean,std,ci95_low,ci95_high
0,heisenberg_19q_pca36_n2000_gpu,classica,ROC-AUC,10,0.843733,0.081463,0.785458,0.902008
1,heisenberg_19q_pca36_n2000_gpu,classica,PR-AUC,10,0.908034,0.086030,0.846492,0.969576
2,heisenberg_19q_pca36_n2000_gpu,classica,Accuracy,10,0.770718,0.093079,0.704133,0.837303
3,heisenberg_19q_pca36_n2000_gpu,classica,Precision,10,0.830759,0.090734,0.765852,0.895666
4,heisenberg_19q_pca36_n2000_gpu,classica,Recall,10,0.812332,0.086797,0.750241,0.874423
5,heisenberg_19q_pca36_n2000_gpu,classica,F1,10,0.820493,0.085396,0.759405,0.881582
6,heisenberg_19q_pca36_n2000_gpu,classica,Specificity,10,0.678487,0.088858,0.614921,0.742052
7,heisenberg_19q_pca36_n2000_gpu,quantum_only,ROC-AUC,10,0.778528,0.115332,0.696024,0.861032
8,heisenberg_19q_pca36_n2000_gpu,quantum_only,PR-AUC,10,0.878059,0.094150,0.810708,0.945410
9,heisenberg_19q_pca36_n2000_gpu,quantum_only,Accuracy,10,0.706630,0.123360,0.618384,0.794876
10,heisenberg_19q_pca36_n2000_gpu,quantum_only,Precision,10,0.792389,0.113952,0.710873,0.873906
11,heisenberg_19q_pca36_n2000_gpu,quantum_only,Recall,10,0.749138,0.150771,0.641284,0.856993
12,heisenberg_19q_pca36_n2000_gpu,quantum_only,F1,10,0.763041,0.119134,0.677817,0.848264
13,heisenberg_19q_pca36_n2000_gpu,quantum_only,Specificity,10,0.607698,0.123922,0.519050,0.696347
14,heisenberg_19q_pca36_n2000_gpu,hibrida,ROC-AUC,10,0.842278,0.090712,0.777387,0.907170
15,heisenberg_19q_pca36_n2000_gpu,hibrida,PR-AUC,10,0.906115,0.090315,0.841507,0.970722
16,heisenberg_19q_pca36_n2000_gpu,hibrida,Accuracy,10,0.780110,0.085899,0.718662,0.841559
17,heisenberg_19q_pca36_n2000_gpu,hibrida,Precision,10,0.843465,0.091263,0.778180,0.908751
18,heisenberg_19q_pca36_n2000_gpu,hibrida,Recall,10,0.811728,0.087195,0.749353,0.874103
19,heisenberg_19q_pca36_n2000_gpu,hibrida,F1,10,0.825969,0.082685,0.766820,0.885118
20,heisenberg_19q_pca36_n2000_gpu,hibrida,Specificity,10,0.720502,0.101374,0.647983,0.793020

## Parte II.C — Diagnóstico de tempo e bond dimensions: Heisenberg 37q/MPS

Este diagnóstico usa duas linhas do outer test do fold 10. Preprocessing e PCA-36 são ajustados somente no respectivo outer train; as duas linhas recebem apenas `transform`. Primeiro a Heisenberg é executada sem limite de bond dimension e com `mps_log_data=True`. Depois, o mesmo teste é repetido com bond dimension limitada.

O tempo por linha é uma aproximação: com apenas duas linhas, o overhead fixo do Estimator tem peso elevado e o escalonamento para lotes maiores pode não ser perfeitamente linear. A projeção para 1.000 amostras estima apenas custo computacional: PCA-36 continua metodologicamente inviável no primeiro inner train dessa amostra, que permite no máximo 24 componentes centralizados.

In [12]:
# ── DUAS LINHAS PARA O BENCHMARK MPS ────────────────────────────────
TIMING_OUTER_FOLD = 10
TIMING_N_ROWS = 2

timing_train_idx, timing_test_idx = OUTER_FOLDS_2000[TIMING_OUTER_FOLD - 1]
X_timing_train_raw = X_2000.iloc[timing_train_idx].copy()
y_timing_train = y_2000.iloc[timing_train_idx].reset_index(drop=True)
X_timing_two_raw = X_2000.iloc[timing_test_idx[:TIMING_N_ROWS]].copy()

# Ajuste somente no outer train; as duas linhas de teste recebem apenas transform.
TIMING_PREPROCESSING_37Q, X_timing_train_all = fit_preprocessing(
    X_timing_train_raw
)
X_TIMING_TWO_ALL = transform_preprocessing(
    TIMING_PREPROCESSING_37Q,
    X_timing_two_raw,
)
TIMING_PCA_37Q, _X_timing_train_pca36 = fit_pca_reducer(
    X_timing_train_all,
    n_components=36,
)
X_TIMING_TWO_PCA36 = transform_pca(
    TIMING_PCA_37Q,
    X_TIMING_TWO_ALL,
)

# Confirma que a reconstrução coincide com o cache leakage-safe do benchmark.
X_timing_cached = (
    CLASSICAL_BENCHMARK_N2000["folds"][TIMING_OUTER_FOLD - 1]
    ["outer_test_representations"]["pca36"]
    .iloc[:TIMING_N_ROWS]
    .reset_index(drop=True)
)
assert np.allclose(X_TIMING_TWO_PCA36, X_timing_cached)
assert X_TIMING_TWO_PCA36.shape == (TIMING_N_ROWS, 36)

# Quantidade real de linhas processadas nos 30 inner + 10 outer transforms.
# O cálculo depende somente dos tamanhos amostrais, não da execução da Parte I.
MPS_WORKLOAD_ROWS = {}
for workload_label, workload_n_samples in (
    ("n1000_workload_real", 1_000),
    ("n2000_workload_real", 2_000),
):
    row_transforms = 0
    transform_calls = 0
    workload_outer_cv = TimeSeriesSplit(n_splits=OUTER_SPLITS)
    for workload_train_idx, workload_test_idx in workload_outer_cv.split(
        np.arange(workload_n_samples)
    ):
        workload_inner_cv = TimeSeriesSplit(n_splits=INNER_SPLITS)
        for workload_inner_train, workload_inner_validation in (
            workload_inner_cv.split(workload_train_idx)
        ):
            row_transforms += len(workload_inner_train)
            row_transforms += len(workload_inner_validation)
            transform_calls += 1
        row_transforms += len(workload_train_idx)
        row_transforms += len(workload_test_idx)
        transform_calls += 1
    MPS_WORKLOAD_ROWS[workload_label] = {
        "transform_calls": transform_calls,
        "row_transforms": row_transforms,
    }

timing_pipeline_summary = pd.DataFrame([
    {"stage": "raw", "rows": len(X_timing_two_raw), "features": X_timing_two_raw.shape[1]},
    {"stage": "preprocessing", "rows": len(X_TIMING_TWO_ALL), "features": X_TIMING_TWO_ALL.shape[1]},
    {"stage": "PCA-36", "rows": len(X_TIMING_TWO_PCA36), "features": X_TIMING_TWO_PCA36.shape[1]},
])
display(timing_pipeline_summary)
display(pd.DataFrame(MPS_WORKLOAD_ROWS).T)
display(X_TIMING_TWO_PCA36)

           stage  rows  features
0            raw     2        36
1  preprocessing     2        78
2         PCA-36     2        36

                     transform_calls  row_transforms
n1000_workload_real               40           17320
n2000_workload_real               40           34469

,PC001,PC002,PC003,PC004,PC005,PC006,PC007,PC008,PC009,PC010,...,PC027,PC028,PC029,PC030,PC031,PC032,PC033,PC034,PC035,PC036
0,-2.666368,2.143983,-0.946535,3.510733,0.149419,-1.228328,1.747141,-0.871413,-1.781509,0.343972,...,0.241321,-1.315711,-0.934489,1.424819,-1.834753,-0.238014,0.388457,-1.018324,0.820946,1.834358
1,1.858655,5.081414,4.553847,0.950828,-2.579757,0.248203,2.014179,0.743017,-1.970098,-2.074839,...,0.814474,-1.487999,0.513256,1.303241,-0.626382,-0.126661,-0.087956,-0.751704,0.379292,-0.012970

In [13]:
# ── TESTE 1: MPS SEM LIMITE DE BOND DIMENSION ──────────────────────
TIMING_RUN_LABEL_UNRESTRICTED = "heisenberg_37q_pca36_timing_unrestricted_mps"
TIMING_SHOTS = SHOTS

HEISENBERG_TIMING_37Q_UNRESTRICTED = HeisenbergProjectiveQFM(
    name_file=TIMING_RUN_LABEL_UNRESTRICTED,
    seed=RANDOM_STATE,
    ideal=True,
    simulation=True,
    fakebackend=False,
    shots=TIMING_SHOTS,
    q_enc=37,
    R=2,
    alpha=0.1,
    use_tanh_scaling=True,
    measure_2local_diagonal=False,
    mps=True,
    use_gpu_statevector=False,
    mps_max_bond_dimension=None,
    mps_truncation_threshold=1e-16,
    output_root=f"outputs/pqfm/{TIMING_RUN_LABEL_UNRESTRICTED}",
)
HEISENBERG_TIMING_37Q_UNRESTRICTED.fit(
    np.zeros((1, 36), dtype=float)
)
HEISENBERG_TIMING_37Q_UNRESTRICTED.backend.set_options(mps_log_data=True)

# O transformer retorna as features, mas não o metadata interno do Aer.
# Esta captura temporária preserva os AerJobs somente para ler MPS_log_data.
MPS_JOBS_UNRESTRICTED = []
_mps_original_run_unrestricted = (
    HEISENBERG_TIMING_37Q_UNRESTRICTED.backend.run
)
HEISENBERG_TIMING_37Q_UNRESTRICTED.backend.run = (
    lambda *args, **kwargs:
        MPS_JOBS_UNRESTRICTED.append(
            _mps_original_run_unrestricted(*args, **kwargs)
        )
        or MPS_JOBS_UNRESTRICTED[-1]
)

try:
    _mps_started_unrestricted = time.perf_counter()
    XQ_TIMING_UNRESTRICTED_37Q = (
        HEISENBERG_TIMING_37Q_UNRESTRICTED.transform(
            X_TIMING_TWO_PCA36
        )
    )
    MPS_SECONDS_UNRESTRICTED = (
        time.perf_counter() - _mps_started_unrestricted
    )
finally:
    HEISENBERG_TIMING_37Q_UNRESTRICTED.backend.run = (
        _mps_original_run_unrestricted
    )

MPS_BOND_DIMENSIONS_UNRESTRICTED = []
MPS_AER_ROWS_UNRESTRICTED = []
for _job_number, _aer_job in enumerate(MPS_JOBS_UNRESTRICTED, 1):
    for _experiment_number, _experiment in enumerate(
        _aer_job.result().results, 1
    ):
        _metadata = _experiment.metadata
        _mps_log = _metadata.get("MPS_log_data", "")
        for _bond_block in re.findall(r"BD=\[([^]]+)\]", _mps_log):
            MPS_BOND_DIMENSIONS_UNRESTRICTED.extend(
                int(value) for value in _bond_block.split()
            )
        MPS_AER_ROWS_UNRESTRICTED.append({
            "job": _job_number,
            "experiment": _experiment_number,
            "time_taken_s": _metadata.get("time_taken", np.nan),
            "sample_measure_time_s": _metadata.get("sample_measure_time", np.nan),
            "method": _metadata.get("method"),
            "device": _metadata.get("device"),
        })

if not MPS_BOND_DIMENSIONS_UNRESTRICTED:
    raise RuntimeError("O Aer não devolveu bond dimensions em MPS_log_data.")

MPS_MAX_BOND_UNRESTRICTED = max(MPS_BOND_DIMENSIONS_UNRESTRICTED)
MPS_SECONDS_PER_ROW_UNRESTRICTED = (
    MPS_SECONDS_UNRESTRICTED / TIMING_N_ROWS
)

_projection_rows_unrestricted = [
    {"workload": "40 × 1.000 (conservador)", "row_transforms": 40_000},
    {"workload": "40 × 2.000 (conservador)", "row_transforms": 80_000},
]
for _label, _workload in MPS_WORKLOAD_ROWS.items():
    _projection_rows_unrestricted.append({
        "workload": _label,
        "row_transforms": _workload["row_transforms"],
    })
for _row in _projection_rows_unrestricted:
    _row["estimated_hours"] = (
        _row["row_transforms"]
        * MPS_SECONDS_PER_ROW_UNRESTRICTED
        / 3600
    )

MPS_TIMING_UNRESTRICTED_SUMMARY = pd.DataFrame([{
    "mode": "unrestricted",
    "rows": TIMING_N_ROWS,
    "quantum_features": XQ_TIMING_UNRESTRICTED_37Q.shape[1],
    "seconds_total": MPS_SECONDS_UNRESTRICTED,
    "seconds_per_row": MPS_SECONDS_PER_ROW_UNRESTRICTED,
    "max_bond_observed": MPS_MAX_BOND_UNRESTRICTED,
    "bond_limit": None,
    "truncation_threshold": 1e-16,
}])
MPS_BOND_COUNTS_UNRESTRICTED = (
    pd.Series(MPS_BOND_DIMENSIONS_UNRESTRICTED, name="bond_dimension")
    .value_counts()
    .sort_index()
    .rename_axis("bond_dimension")
    .reset_index(name="occurrences")
)

display(MPS_TIMING_UNRESTRICTED_SUMMARY)
display(MPS_BOND_COUNTS_UNRESTRICTED)
display(pd.DataFrame(_projection_rows_unrestricted))
display(pd.DataFrame(XQ_TIMING_UNRESTRICTED_37Q))

,mode,rows,quantum_features,seconds_total,seconds_per_row,max_bond_observed,bond_limit,truncation_threshold
0,unrestricted,2,111,3.44361,1.721805,10,None,1.000000e-16

   bond_dimension  occurrences
0               1        39690
1               2        45780
2               3           36
3               4        42501
4               5         2865
5               6         4101
6               7        11448
7               8        16083
8               9          516
9              10          276

                   workload  row_transforms  estimated_hours
0  40 × 1.000 (conservador)           40000        19.131167
1  40 × 2.000 (conservador)           80000        38.262335
2       n1000_workload_real           17320         8.283795
3       n2000_workload_real           34469        16.485805

,0,1,2,3,4,5,6,7,8,9,...,101,102,103,104,105,106,107,108,109,110
0,0.660645,0.473633,0.187500,-0.771484,0.139160,-0.224609,0.152832,0.302246,-0.937988,0.517578,...,-0.945801,0.833496,-0.248535,-0.435059,0.797852,-0.465332,-0.301758,0.784180,0.343262,0.410645
1,0.749512,0.519043,0.446777,-0.838867,0.004395,-0.537598,0.070801,0.357910,-0.936523,0.526367,...,-0.947266,0.722656,-0.428223,-0.404785,0.836914,0.247559,-0.409180,0.743164,-0.342773,0.550293

In [15]:
# ── TESTE 2: MPS COM BOND DIMENSION LIMITADA ───────────────────────
# Valor inicial: metade da maior bond observada, nunca maior que 64.
# Edite esta variável se quiser testar outro limite.
MPS_LIMITED_MAX_BOND_DIMENSION = min(
    64,
    max(1, MPS_MAX_BOND_UNRESTRICTED // 2),
)
TIMING_RUN_LABEL_LIMITED = (
    f"heisenberg_37q_pca36_timing_bond_{MPS_LIMITED_MAX_BOND_DIMENSION}"
)

HEISENBERG_TIMING_37Q_LIMITED = HeisenbergProjectiveQFM(
    name_file=TIMING_RUN_LABEL_LIMITED,
    seed=RANDOM_STATE,
    ideal=True,
    simulation=True,
    fakebackend=False,
    shots=TIMING_SHOTS,
    q_enc=37,
    R=2,
    alpha=0.1,
    use_tanh_scaling=True,
    measure_2local_diagonal=False,
    mps=True,
    use_gpu_statevector=False,
    mps_max_bond_dimension=MPS_LIMITED_MAX_BOND_DIMENSION,
    mps_truncation_threshold=1e-16,
    output_root=f"outputs/pqfm/{TIMING_RUN_LABEL_LIMITED}",
)
HEISENBERG_TIMING_37Q_LIMITED.fit(
    np.zeros((1, 36), dtype=float)
)
HEISENBERG_TIMING_37Q_LIMITED.backend.set_options(mps_log_data=True)

MPS_JOBS_LIMITED = []
_mps_original_run_limited = HEISENBERG_TIMING_37Q_LIMITED.backend.run
HEISENBERG_TIMING_37Q_LIMITED.backend.run = (
    lambda *args, **kwargs:
        MPS_JOBS_LIMITED.append(
            _mps_original_run_limited(*args, **kwargs)
        )
        or MPS_JOBS_LIMITED[-1]
)

try:
    _mps_started_limited = time.perf_counter()
    XQ_TIMING_LIMITED_37Q = HEISENBERG_TIMING_37Q_LIMITED.transform(
        X_TIMING_TWO_PCA36
    )
    MPS_SECONDS_LIMITED = time.perf_counter() - _mps_started_limited
finally:
    HEISENBERG_TIMING_37Q_LIMITED.backend.run = (
        _mps_original_run_limited
    )

MPS_BOND_DIMENSIONS_LIMITED = []
MPS_AER_ROWS_LIMITED = []
for _job_number, _aer_job in enumerate(MPS_JOBS_LIMITED, 1):
    for _experiment_number, _experiment in enumerate(
        _aer_job.result().results, 1
    ):
        _metadata = _experiment.metadata
        _mps_log = _metadata.get("MPS_log_data", "")
        for _bond_block in re.findall(r"BD=\[([^]]+)\]", _mps_log):
            MPS_BOND_DIMENSIONS_LIMITED.extend(
                int(value) for value in _bond_block.split()
            )
        MPS_AER_ROWS_LIMITED.append({
            "job": _job_number,
            "experiment": _experiment_number,
            "time_taken_s": _metadata.get("time_taken", np.nan),
            "sample_measure_time_s": _metadata.get("sample_measure_time", np.nan),
            "method": _metadata.get("method"),
            "device": _metadata.get("device"),
        })

if not MPS_BOND_DIMENSIONS_LIMITED:
    raise RuntimeError("O Aer não devolveu bond dimensions no teste limitado.")

MPS_SECONDS_PER_ROW_LIMITED = MPS_SECONDS_LIMITED / TIMING_N_ROWS
MPS_ABSOLUTE_DIFFERENCE = np.abs(
    XQ_TIMING_LIMITED_37Q - XQ_TIMING_UNRESTRICTED_37Q
)

_projection_rows_limited = []
for _row in _projection_rows_unrestricted:
    _projection_rows_limited.append({
        "workload": _row["workload"],
        "row_transforms": _row["row_transforms"],
        "estimated_hours_unrestricted": _row["estimated_hours"],
        "estimated_hours_limited": (
            _row["row_transforms"]
            * MPS_SECONDS_PER_ROW_LIMITED
            / 3600
        ),
    })

MPS_TIMING_COMPARISON = pd.DataFrame([
    {
        "mode": "unrestricted",
        "bond_limit": None,
        "max_bond_observed": MPS_MAX_BOND_UNRESTRICTED,
        "seconds_total": MPS_SECONDS_UNRESTRICTED,
        "seconds_per_row": MPS_SECONDS_PER_ROW_UNRESTRICTED,
        "speedup_vs_unrestricted": 1.0,
        "mean_abs_feature_difference": 0.0,
        "max_abs_feature_difference": 0.0,
    },
    {
        "mode": "limited",
        "bond_limit": MPS_LIMITED_MAX_BOND_DIMENSION,
        "max_bond_observed": max(MPS_BOND_DIMENSIONS_LIMITED),
        "seconds_total": MPS_SECONDS_LIMITED,
        "seconds_per_row": MPS_SECONDS_PER_ROW_LIMITED,
        "speedup_vs_unrestricted": (
            MPS_SECONDS_UNRESTRICTED / MPS_SECONDS_LIMITED
        ),
        "mean_abs_feature_difference": MPS_ABSOLUTE_DIFFERENCE.mean(),
        "max_abs_feature_difference": MPS_ABSOLUTE_DIFFERENCE.max(),
    },
])
MPS_BOND_COUNTS_LIMITED = (
    pd.Series(MPS_BOND_DIMENSIONS_LIMITED, name="bond_dimension")
    .value_counts()
    .sort_index()
    .rename_axis("bond_dimension")
    .reset_index(name="occurrences")
)

display(MPS_TIMING_COMPARISON)
display(MPS_BOND_COUNTS_LIMITED)
display(pd.DataFrame(_projection_rows_limited))
display(pd.DataFrame(XQ_TIMING_LIMITED_37Q))

,mode,bond_limit,max_bond_observed,seconds_total,seconds_per_row,speedup_vs_unrestricted,mean_abs_feature_difference,max_abs_feature_difference
0,unrestricted,NaN,10,3.443610,1.721805,1.000000,0.0,0.0
1,limited,5.0,10,3.288037,1.644018,1.047315,0.0,0.0

   bond_dimension  occurrences
0               1       107730
1               2       124260
2               3           90
3               4       115383
4               5        39159
5               6         7200
6               7        19386
7               8        28566
8               9          630
9              10          828

,workload,row_transforms,estimated_hours_unrestricted,estimated_hours_limited
0,40 × 1.000 (conservador),40000,19.131167,18.266870
1,40 × 2.000 (conservador),80000,38.262335,36.533740
2,n1000_workload_real,17320,8.283795,7.909555
3,n2000_workload_real,34469,16.485805,15.741018

,0,1,2,3,4,5,6,7,8,9,...,101,102,103,104,105,106,107,108,109,110
0,0.660645,0.473633,0.187500,-0.771484,0.139160,-0.224609,0.152832,0.302246,-0.937988,0.517578,...,-0.945801,0.833496,-0.248535,-0.435059,0.797852,-0.465332,-0.301758,0.784180,0.343262,0.410645
1,0.749512,0.519043,0.446777,-0.838867,0.004395,-0.537598,0.070801,0.357910,-0.936523,0.526367,...,-0.947266,0.722656,-0.428223,-0.404785,0.836914,0.247559,-0.409180,0.743164,-0.342773,0.550293

## Parte II.D — Heisenberg 37q × PCA-36, CPU/MPS

Trinta e sete qubits formam uma cadeia com 36 arestas. As 36 componentes PCA ocupam exatamente um bloco. O backend usa `matrix_product_state` em CPU, sem limite de bond dimension e com o limiar conservador padrão `1e-16`.

PCA-36 é usado somente para o encoding quântico. O baseline clássico usa todas as features preprocessadas e o híbrido concatena todas as features clássicas com as 111 features quânticas locais Z/X/Y.

In [ ]:
# ── CONFIGURAÇÃO EDITÁVEL DESTA CÉLULA ──────────────────────────────
RUN_LABEL = "heisenberg_37q_pca36_n2000_cpu_mps"
N_QUBITS = 37
N_PCA_COMPONENTS = 36
HEISENBERG_R = 2
HEISENBERG_ALPHA = 0.1
HEISENBERG_SHOTS = SHOTS
USE_TANH_SCALING = True
MEASURE_2LOCAL_DIAGONAL = False
CLASSICAL_BENCHMARK = CLASSICAL_BENCHMARK_N2000
PCA_REPRESENTATION = "pca36"
MPS_MAX_BOND_DIMENSION = None
MPS_TRUNCATION_THRESHOLD = 1e-16
# ────────────────────────────────────────────────────────────────────

HEISENBERG_CACHE_KEY_37Q = (
    RUN_LABEL,
    id(CLASSICAL_BENCHMARK),
    RANDOM_STATE,
    N_QUBITS,
    N_PCA_COMPONENTS,
    HEISENBERG_R,
    HEISENBERG_ALPHA,
    HEISENBERG_SHOTS,
    USE_TANH_SCALING,
    MEASURE_2LOCAL_DIAGONAL,
    MPS_MAX_BOND_DIMENSION,
    MPS_TRUNCATION_THRESHOLD,
)
cache_is_current = (
    "HEISENBERG_PCA_CACHE_37Q_N2000" in globals()
    and HEISENBERG_PCA_CACHE_37Q_N2000.get("cache_key")
    == HEISENBERG_CACHE_KEY_37Q
)

if cache_is_current:
    print("Cache Heisenberg 37q/PCA-36/n2000 CPU-MPS já existe; reutilizando.")
else:
    HEISENBERG_PQFM_37Q = HeisenbergProjectiveQFM(
        name_file=RUN_LABEL,
        seed=RANDOM_STATE,
        ideal=True,
        simulation=True,
        fakebackend=False,
        shots=HEISENBERG_SHOTS,
        q_enc=N_QUBITS,
        R=HEISENBERG_R,
        alpha=HEISENBERG_ALPHA,
        use_tanh_scaling=USE_TANH_SCALING,
        measure_2local_diagonal=MEASURE_2LOCAL_DIAGONAL,
        mps=True,
        use_gpu_statevector=False,
        mps_max_bond_dimension=MPS_MAX_BOND_DIMENSION,
        mps_truncation_threshold=MPS_TRUNCATION_THRESHOLD,
        output_root=f"outputs/pqfm/{RUN_LABEL}",
    )
    print("Preparando uma única vez o circuito Heisenberg 37q em CPU/MPS...")
    HEISENBERG_PQFM_37Q.fit(
        np.zeros((1, N_PCA_COMPONENTS), dtype=float)
    )
    assert HEISENBERG_PQFM_37Q.backend.options.method == "matrix_product_state"
    assert HEISENBERG_PQFM_37Q.backend.options.device == "CPU"
    assert HEISENBERG_PQFM_37Q.theta_info["features_per_block"] == 36
    assert HEISENBERG_PQFM_37Q.theta_info["num_blocks"] == 1
    assert HEISENBERG_PQFM_37Q.theta_info["total_slots"] == 36

    quantum_folds = []
    transform_counter = 0
    transform_total = len(CLASSICAL_BENCHMARK["folds"]) * (INNER_SPLITS + 1)

    for classic_fold in CLASSICAL_BENCHMARK["folds"]:
        outer_fold = classic_fold["outer_fold"]
        inner_quantum = []
        for inner_data in classic_fold["inner_folds"]:
            X_train_pca = inner_data["train_representations"][PCA_REPRESENTATION]
            X_validation_pca = inner_data["validation_representations"][PCA_REPRESENTATION]
            n_train = len(X_train_pca)
            X_all_pca = pd.concat(
                [X_train_pca, X_validation_pca],
                ignore_index=True,
            )
            transform_counter += 1
            print(
                f"[Heisenberg-37q {transform_counter:02d}/{transform_total:02d}] "
                f"outer={outer_fold}/10 | inner={inner_data['inner_fold']}/3 | "
                f"amostras={len(X_all_pca)} | CPU/MPS"
            )
            started_at = time.perf_counter()
            Xq_values = HEISENBERG_PQFM_37Q.transform(X_all_pca)
            q_columns = [f"heisenberg_q_{i}" for i in range(Xq_values.shape[1])]
            Xq_all = pd.DataFrame(Xq_values, columns=q_columns)
            inner_quantum.append({
                "inner_fold": inner_data["inner_fold"],
                "X_train_quantum": Xq_all.iloc[:n_train].reset_index(drop=True),
                "X_validation_quantum": Xq_all.iloc[n_train:].reset_index(drop=True),
            })
            print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        X_outer_train_pca = classic_fold["outer_train_representations"][PCA_REPRESENTATION]
        X_outer_test_pca = classic_fold["outer_test_representations"][PCA_REPRESENTATION]
        n_outer_train = len(X_outer_train_pca)
        X_outer_all_pca = pd.concat(
            [X_outer_train_pca, X_outer_test_pca],
            ignore_index=True,
        )
        transform_counter += 1
        print(
            f"[Heisenberg-37q {transform_counter:02d}/{transform_total:02d}] "
            f"outer={outer_fold}/10 | OUTER | "
            f"amostras={len(X_outer_all_pca)} | CPU/MPS"
        )
        started_at = time.perf_counter()
        Xq_outer_values = HEISENBERG_PQFM_37Q.transform(X_outer_all_pca)
        q_columns = [
            f"heisenberg_q_{i}" for i in range(Xq_outer_values.shape[1])
        ]
        Xq_outer_all = pd.DataFrame(Xq_outer_values, columns=q_columns)
        print(f"  concluído em {time.perf_counter() - started_at:.1f}s")

        quantum_folds.append({
            "classic_fold": classic_fold,
            "inner_quantum": inner_quantum,
            "X_outer_train_quantum": Xq_outer_all.iloc[:n_outer_train].reset_index(drop=True),
            "X_outer_test_quantum": Xq_outer_all.iloc[n_outer_train:].reset_index(drop=True),
        })

    HEISENBERG_PCA_CACHE_37Q_N2000 = {
        "cache_key": HEISENBERG_CACHE_KEY_37Q,
        "config": RUN_LABEL,
        "pca_representation": PCA_REPRESENTATION,
        "n_qubits": N_QUBITS,
        "n_input_features": N_PCA_COMPONENTS,
        "n_blocks": HEISENBERG_PQFM_37Q.theta_info["num_blocks"],
        "n_quantum_features": len(q_columns),
        "folds": quantum_folds,
    }
    print(
        f"Cache concluído: {len(quantum_folds)} outer folds | "
        f"{len(q_columns)} features quânticas por amostra."
    )

Preparando uma única vez o circuito Heisenberg 37q em CPU/MPS...
[Heisenberg-37q 01/40] outer=1/10 | inner=1/3 | amostras=96 | CPU/MPS
  concluído em 192.7s
[Heisenberg-37q 02/40] outer=1/10 | inner=2/3 | amostras=143 | CPU/MPS
  concluído em 291.5s
[Heisenberg-37q 03/40] outer=1/10 | inner=3/3 | amostras=190 | CPU/MPS
  concluído em 391.9s
[Heisenberg-37q 04/40] outer=1/10 | OUTER | amostras=371 | CPU/MPS

In [ ]:
# Nested tuning e avaliação. Esta célula não chama a PQFM.
RUN_LABEL = HEISENBERG_PCA_CACHE_37Q_N2000["config"]
candidates = list(ParameterGrid(CLASSIFIER_GRID))
fold_rows = []
tuning_rows = []

for quantum_fold in HEISENBERG_PCA_CACHE_37Q_N2000["folds"]:
    classic_fold = quantum_fold["classic_fold"]
    outer_fold = classic_fold["outer_fold"]
    print(f"\n[{RUN_LABEL}] tuning/classificação outer fold {outer_fold}/10")
    scores = {
        "quantum_only": {candidate_key(params): [] for params in candidates},
        "hibrida": {candidate_key(params): [] for params in candidates},
    }

    for inner_data, inner_quantum in zip(
        classic_fold["inner_folds"],
        quantum_fold["inner_quantum"],
        strict=True,
    ):
        X_train_classical = inner_data["train_representations"]["all_features"]
        X_validation_classical = inner_data["validation_representations"]["all_features"]
        X_train_quantum = inner_quantum["X_train_quantum"]
        X_validation_quantum = inner_quantum["X_validation_quantum"]
        X_train_hybrid = pd.concat(
            [X_train_classical.reset_index(drop=True), X_train_quantum], axis=1
        )
        X_validation_hybrid = pd.concat(
            [X_validation_classical.reset_index(drop=True), X_validation_quantum], axis=1
        )

        for params in candidates:
            key = candidate_key(params)
            scores["quantum_only"][key].append(
                fit_and_score_classifier(
                    X_train_quantum,
                    inner_data["y_train"],
                    X_validation_quantum,
                    inner_data["y_validation"],
                    params,
                )
            )
            scores["hibrida"][key].append(
                fit_and_score_classifier(
                    X_train_hybrid,
                    inner_data["y_train"],
                    X_validation_hybrid,
                    inner_data["y_validation"],
                    params,
                )
            )

    best_params = {}
    for scenario in ("quantum_only", "hibrida"):
        mean_scores = {
            key: float(np.mean(values))
            for key, values in scores[scenario].items()
        }
        best_key = max(mean_scores, key=mean_scores.get)
        best_params[scenario] = json.loads(best_key)
        for key, values in scores[scenario].items():
            tuning_rows.append({
                "config": RUN_LABEL,
                "outer_fold": outer_fold,
                "scenario": scenario,
                "params": key,
                "mean_inner_average_precision": np.mean(values),
                "std_inner_average_precision": np.std(values, ddof=1),
            })

    fold_rows.append({
        "config": RUN_LABEL,
        "scenario": "classica",
        "outer_fold": outer_fold,
        "n_train": len(classic_fold["train_idx"]),
        "n_test": len(classic_fold["test_idx"]),
        "test_start_position": int(classic_fold["test_idx"][0]),
        "test_end_position": int(classic_fold["test_idx"][-1]),
        "best_params": json.dumps(
            classic_fold["best_params"]["all_features"], sort_keys=True
        ),
        **classic_fold["classic_metrics"]["all_features"],
    })

    X_outer_train_classical = classic_fold["outer_train_representations"]["all_features"]
    X_outer_test_classical = classic_fold["outer_test_representations"]["all_features"]
    X_outer_train_quantum = quantum_fold["X_outer_train_quantum"]
    X_outer_test_quantum = quantum_fold["X_outer_test_quantum"]
    X_outer_train_hybrid = pd.concat(
        [X_outer_train_classical.reset_index(drop=True), X_outer_train_quantum], axis=1
    )
    X_outer_test_hybrid = pd.concat(
        [X_outer_test_classical.reset_index(drop=True), X_outer_test_quantum], axis=1
    )

    for scenario, X_train_rep, X_test_rep in (
        ("quantum_only", X_outer_train_quantum, X_outer_test_quantum),
        ("hibrida", X_outer_train_hybrid, X_outer_test_hybrid),
    ):
        params = best_params[scenario]
        classifier = GradientBoostingClassifier(
            random_state=RANDOM_STATE,
            **params,
        )
        classifier.fit(X_train_rep, classic_fold["y_outer_train"])
        prediction = classifier.predict(X_test_rep)
        probability = classifier.predict_proba(X_test_rep)[:, 1]
        fold_rows.append({
            "config": RUN_LABEL,
            "scenario": scenario,
            "outer_fold": outer_fold,
            "n_train": len(classic_fold["train_idx"]),
            "n_test": len(classic_fold["test_idx"]),
            "test_start_position": int(classic_fold["test_idx"][0]),
            "test_end_position": int(classic_fold["test_idx"][-1]),
            "best_params": json.dumps(params, sort_keys=True),
            **compute_metrics(
                classic_fold["y_outer_test"], prediction, probability
            ),
        })

    checkpoint = {
        "config": RUN_LABEL,
        "fold_results": pd.DataFrame(fold_rows),
        "tuning_results": pd.DataFrame(tuning_rows),
    }
    with open(
        CHECKPOINT_DIR / f"{RUN_LABEL}_fold_{outer_fold:02d}.pkl",
        "wb",
    ) as handle:
        pickle.dump(checkpoint, handle)

HEISENBERG_37Q_PCA36_N2000_RESULT = {
    "config": RUN_LABEL,
    "fold_results": pd.DataFrame(fold_rows),
    "tuning_results": pd.DataFrame(tuning_rows),
}
print(f"Experimento {RUN_LABEL} concluído.")

In [ ]:
HEISENBERG_37Q_SUMMARY = summarize_quantum_results(
    HEISENBERG_37Q_PCA36_N2000_RESULT["fold_results"]
)
HEISENBERG_37Q_STATS = quantum_statistical_analysis(
    HEISENBERG_37Q_PCA36_N2000_RESULT["fold_results"],
    title="HEISENBERG 37Q × PCA-36 × N2000 × CPU/MPS — 10 OUTER FOLDS",
)
display(HEISENBERG_37Q_PCA36_N2000_RESULT["fold_results"])
display(HEISENBERG_37Q_SUMMARY)

## Resumo descritivo final

As amostras de 1.000 e 2.000 registros são diferentes. Portanto, esta tabela é apenas descritiva; testes pareados são feitos somente dentro de cada tamanho amostral e arquitetura.

In [ ]:
FINAL_CLASSICAL_SUMMARY = pd.concat(
    [CLASSICAL_SUMMARY_N1000, CLASSICAL_SUMMARY_N2000],
    ignore_index=True,
)
FINAL_HEISENBERG_SUMMARY = pd.concat(
    [HEISENBERG_13Q_SUMMARY, HEISENBERG_19Q_SUMMARY, HEISENBERG_37Q_SUMMARY],
    ignore_index=True,
)

display(FINAL_CLASSICAL_SUMMARY)
display(FINAL_HEISENBERG_SUMMARY)